import Foundation

enum LocalizationStrings {
    // swiftlint:disable all
    static let all: [String: [String: String]] = [
        "en": en,
        "zh-Hans": zhHans,
        "zh-Hant-HK": zhHantHK,
        "zh-Hant-TW": zhHantTW,
        "ja": ja,
        "ko": ko,
        "fr": fr,
        "de": de,
        "ru": ru,
    ]

    // MARK: - English (Base)

    private static let en: [String: String] = [
        // App / Navigation
        "app.status": "Status",
        "app.models": "Models",
        "app.downloads": "Downloads",
        "app.chat": "Playground",
        "app.agents": "Agents",
        "app.settings": "Settings",
        "app.running": "Running",
        "app.stopped": "Stopped",
        "app.modelsLoaded": "%d model(s) loaded",
        "app.nova": "Nova",
        "app.mlx": "MLX",
        "app.novamlx": "NovaMLX",

        // Status Page
        "status.serverOnline": "Server Online",
        "status.serverOffline": "Server Offline",
        "status.tokensPerSec": "tokens/sec",
        "status.peakTokensPerSec": "peak tok/s",
        "status.realtimeInferenceSpeed": "Real-time Inference Speed",
        "status.noActivity": "No inference activity yet",
        "status.time": "Time",
        "status.tokPerSec": "tok/s",
        "status.cpu": "CPU",
        "status.memory": "Memory",
        "status.gpu": "GPU",
        "status.uptime": "Uptime",
        "status.requests": "Requests",
        "status.models": "Models",
        "status.disk": "Disk",
        "status.totalTokens": "Total Tokens",
        "status.active": "active",
        "status.loaded": "loaded",
        "status.device": "Device",
        "status.chip": "Chip",
        "status.gpuCores": "GPU Cores",
        "status.cpuCores": "CPU Cores",
        "status.activeModels": "Active Models",
        "status.noModelsLoaded": "No models loaded. Go to Models to download and load one.",
        "status.ready": "Ready",
        "status.kv": "KV",
        "status.hour": "h",
        "status.minute": "m",
        "status.million": "M",
        "status.thousand": "K",

        // Models Page
        "models.myModels": "My Models",
        "models.downloads": "Downloads",
        "models.deleteConfirm": "Delete Model?",
        "models.deleteMessage": "This will permanently remove '%@' from disk. This cannot be undone.",
        "models.downloading": "Downloading",
        "models.completed": "Completed",
        "models.noDownloads": "No Downloads",
        "models.noDownloadsSub": "Search for models or paste a URL to start downloading.",
        "models.noModelsLoaded": "No models loaded",
        "models.noModelsLoadedSub": "Load a downloaded model to start using it.",
        "models.noInactiveModels": "No inactive models",
        "models.noInactiveModelsSub": "Go to Browse to search and download models.",
        "models.searchResults": "Search Results",
        "models.manualDownload": "Manual Download",
        "models.search": "Search",
        "models.download": "Download",
        "models.downloaded": "Downloaded",
        "models.resume": "Resume",
        "models.cancel": "Cancel",
        "models.delete": "Delete",
        "models.retry": "Retry",
        "models.unload": "Unload",
        "models.load": "Load",
        "models.close": "Close",
        "models.loading": "Loading...",
        "models.downloadedOk": "Downloaded successfully",
        "models.retrying": "retrying...",
        "models.downloadedLabel": "downloaded",
        "models.clickDetails": "Click to view model details",
        "models.openFolder": "Open download folder",
        "models.clickCopy": "Click to copy path",
        "models.urlHint": "Paste a HuggingFace repo ID or URL to download directly.",
        "models.savedTo": "Saved to: %@",
        "models.searchPlaceholder": "Search HuggingFace models...",
        "models.urlPlaceholder": "mlx-community/model-name or https://huggingface.co/...",
        "models.tags": "Tags",
        "models.specifications": "Specifications",
        "models.architecture": "Architecture",
        "models.modelType": "Model Type",
        "models.license": "License",
        "models.language": "Language",
        "models.family": "Family",
        "models.type": "Type",
        "models.size": "Size",
        "models.downloadSize": "Download Size",
        "models.diskUsage": "Disk Usage",
        "models.files": "Files (%d)",
        "models.unknown": "unknown",
        "models.filesCompleted": "%d/%d files completed",
        "models.apiKeyRequired": "API Key Required",
        "models.apiKeyMessage": "The Admin API requires an API key to enable model search. A key has been auto-generated below.",
        "models.apiKeyLabel": "API Key:",
        "models.saveRestart": "Save & Restart",
        "models.apiKeyPlaceholder": "sk-novamlx-...",
        "models.invalidUrl": "Invalid URL",
        "models.searchFailed": "Search failed (HTTP %d)",
        "models.noResults": "No results found for '%@'",
        "models.unexpectedFormat": "Unexpected response format",
        "models.searchFailedMsg": "Search failed: %@",
        "models.invalidHfUrl": "Invalid HuggingFace URL",
        "models.invalidUrlMsg": "Invalid URL. Expected: https://huggingface.co/owner/repo",
        "models.saveFailed": "Failed to save API key: %@",
        "models.gb": "GB",
        "models.mb": "MB",
        "models.cloudModels": "Cloud Models",
        "models.noCloudModels": "No cloud models available",
        "models.noCloudModelsSub": "Remote models will appear here when connected",

        // Chat Page
        "chat.model": "Model",
        "chat.noModels": "No models loaded",
        "chat.clear": "Clear",
        "chat.toggleParams": "Toggle parameter settings",
        "chat.rawOutput": "Raw model output viewer — not designed for daily chat use.",
        "chat.webChat": "Web Chat",
        "chat.temperature": "Temperature",
        "chat.topP": "Top P",
        "chat.topK": "Top K",
        "chat.minP": "Min P",
        "chat.maxTokens": "Max Tokens",
        "chat.repeatPenalty": "Repeat Penalty",
        "chat.resetDefault": "Reset to Default",
        "chat.startConversation": "Start a conversation",
        "chat.selectModel": "Select a model above and type a message below.",
        "chat.you": "You",
        "chat.assistant": "Assistant",
        "chat.typePlaceholder": "Type a message...",
        "chat.noResponse": "(no response)",
        "chat.error": "Error: %@",
        "chat.thinking": "Thinking",

        // Settings Page
        "settings.server": "Server",
        "settings.cli": "Command Line Tool",
        "settings.turboQuant": "KV Quantization (TurboQuant)",
        "settings.sessions": "Sessions",
        "settings.about": "About",
        "settings.editConfig": "Edit Config",
        "settings.openChat": "Open Chat in Browser",
        "settings.openDashboard": "Open Dashboard",
        "settings.openConfig": "Open Config File",
        "settings.language": "Language",
        "settings.inferenceApi": "Inference API",
        "settings.adminApi": "Admin API",
        "settings.webChat": "Web Chat",
        "settings.adminDashboard": "Admin Dashboard",
        "settings.configFile": "Config File",
        "settings.version": "Version",
        "settings.build": "Build",
        "settings.license": "License",
        "settings.platform": "Platform",
        "settings.serverConfig": "Server Configuration",
        "settings.host": "Host",
        "settings.port": "Port",
        "settings.adminPort": "Admin Port",
        "settings.maxConcurrent": "Max Concurrent",
        "settings.timeout": "Timeout (s)",
        "settings.maxBody": "Max Body (MB)",
        "settings.defaultModel": "Default Model",
        "settings.apiKeys": "API Keys (one per line)",
        "settings.clickCopy": "Click to copy path",
        "settings.hostPlaceholder": "127.0.0.1",
        "settings.modelPlaceholder": "e.g. mlx-community/Qwen3-35B-4bit",
        "settings.installCli": "Install the `nova` CLI to your PATH",
        "settings.installed": "Installed",
        "settings.alreadyInstalled": "Already installed",
        "settings.cliNotFound": "CLI binary not found in app bundle",
        "settings.cliInstallSuccess": "Installed! Add ~/.local/bin to your PATH if needed.",
        "settings.turboQuantDesc": "Compresses KV cache to reduce GPU memory. Check Status page GPU metric to see the effect.",
        "settings.loadModel": "Load a model to configure KV quantization.",
        "settings.noSessions": "No active sessions",
        "settings.off": "Off",
        "settings.bit8": "8-bit",
        "settings.bit4": "4-bit",
        "settings.bit2": "2-bit",
        "settings.portError": "Error: Port must be 1-65535",
        "settings.adminPortError": "Error: Admin port must be 1-65535",
        "settings.portConflict": "Error: Port and Admin Port must differ",
        "settings.concurrentError": "Error: Max Concurrent must be > 0",
        "settings.savedRestart": "Saved! Restart app to apply changes.",
        "settings.systemDefault": "System Default",
        "settings.licenseValue": "Apache 2.0",
        "settings.refresh": "Refresh",
        "settings.clearAll": "Clear All",
        "settings.resetCurrent": "Reset to Current",
        "settings.saveToDisk": "Save to Disk",
        "settings.save": "Save",
        "settings.cancel": "Cancel",
        "settings.reset": "Reset",
        "settings.memoryLimit": "Memory Limit",
        "settings.memoryLimitAuto": "Auto",
        "settings.memoryLimitPercent": "% of RAM",
        "settings.memoryLimitFixed": "Fixed Value",
        "settings.memoryLimitAutoDesc": "Reserves max(4GB, 20% RAM) for the system, capped at 8GB. The rest is available to NovaMLX.",
        "settings.memoryLimitPercentLabel": "Percent",
        "settings.memoryLimitValueLabel": "Value",
        "settings.memoryLimitGB": "GB",
        "settings.memoryLimitMB": "MB",

        // Agents Page
        "agents.integrations": "Agent Integrations",
        "agents.configLabel": "Configuration",
        "agents.description": "Connect agent tools to NovaMLX as their inference backend. NovaMLX exposes an OpenAI-compatible API that these agents can use directly.",
        "agents.serverRunning": "NovaMLX server running at %@",
        "agents.serverNotRunning": "NovaMLX server is not running — agents cannot connect",
        "agents.installed": "Installed",
        "agents.notFound": "Not Found",
        "agents.refreshStatus": "Refresh agent status",
        "agents.checkInstalled": "Check Installed Agents",
        "agents.launch": "Launch",
        "agents.install": "Install",
        "agents.copyConfig": "Copy Config",
        "agents.configCopied": "%@: Config copied to clipboard",
        "agents.launched": "%@: Launched",
        "agents.launchError": "%@: %@",
        "agents.openclaw": "OpenClaw",
        "agents.hermes": "Hermes Agent",
        "agents.opencode": "OpenCode",
        "agents.openclawDesc": "Open-source AI agent framework with plugin system and tool use",
        "agents.hermesDesc": "Autonomous AI agent with multi-step reasoning and tool execution",
        "agents.opencodeDesc": "Terminal-based AI programming assistant with code editing",

        // Dashboard
        "dashboard.loadedModels": "Loaded Models",
        "dashboard.noModelsLoaded": "No models loaded",
        "dashboard.availableModels": "Available Models",
        "dashboard.noDownloadedModels": "No downloaded models found",
        "dashboard.system": "system",
        "dashboard.used": "used",
        "dashboard.usage": "usage",
        "dashboard.session": "session",
        "dashboard.cores": "cores",
        "dashboard.load": "Load",

        // Menu Bar
        "menuBar.openWindow": "Open Window",
        "menuBar.quit": "Quit",

        // Menu Views
        "menu.noModels": "No models loaded",
        "menu.downloadedCount": "Downloaded: %d model(s)",
        "menu.diskUsage": "Disk usage: %@",
    ]

    // MARK: - Simplified Chinese

    private static let zhHans: [String: String] = [
        "app.status": "状态",
        "app.models": "模型",
        "app.chat": "Playground",
        "app.agents": "智能体",
        "app.settings": "设置",
        "app.running": "运行中",
        "app.stopped": "已停止",
        "app.modelsLoaded": "已加载 %d 个模型",
        "app.nova": "Nova",
        "app.mlx": "MLX",
        "app.novamlx": "NovaMLX",

        "status.serverOnline": "服务器在线",
        "status.serverOffline": "服务器离线",
        "status.tokensPerSec": "token/秒",
        "status.peakTokensPerSec": "峰值 tok/s",
        "status.realtimeInferenceSpeed": "实时推理速度",
        "status.noActivity": "暂无推理活动",
        "status.time": "时间",
        "status.tokPerSec": "token/秒",
        "status.cpu": "CPU",
        "status.memory": "内存",
        "status.gpu": "GPU",
        "status.uptime": "运行时间",
        "status.requests": "请求数",
        "status.models": "模型",
        "status.disk": "磁盘",
        "status.totalTokens": "总 Token 数",
        "status.active": "活跃",
        "status.loaded": "已加载",
        "status.device": "设备",
        "status.chip": "芯片",
        "status.gpuCores": "GPU 核心数",
        "status.cpuCores": "CPU 核心数",
        "status.activeModels": "活跃模型",
        "status.noModelsLoaded": "尚未加载模型。前往「模型」页面下载并加载。",
        "status.ready": "就绪",
        "status.kv": "KV",
        "status.hour": "时",
        "status.minute": "分",
        "status.million": "M",
        "status.thousand": "K",

        "models.myModels": "我的模型",
        "models.downloads": "下载",
        "models.deleteConfirm": "删除模型？",
        "models.deleteMessage": "将永久删除「%@」，此操作不可撤销。",
        "models.downloading": "下载中",
        "models.completed": "已完成",
        "models.noDownloads": "暂无下载",
        "models.noDownloadsSub": "搜索模型或粘贴 URL 开始下载。",
        "models.noModelsLoaded": "未加载模型",
        "models.noModelsLoadedSub": "加载已下载的模型以开始使用。",
        "models.noInactiveModels": "无未激活模型",
        "models.noInactiveModelsSub": "前往浏览页面搜索并下载模型。",
        "models.searchResults": "搜索结果",
        "models.manualDownload": "手动下载",
        "models.search": "搜索",
        "models.download": "下载",
        "models.downloaded": "已下载",
        "models.resume": "继续",
        "models.cancel": "取消",
        "models.delete": "删除",
        "models.retry": "重试",
        "models.unload": "卸载",
        "models.load": "加载",
        "models.close": "关闭",
        "models.loading": "加载中...",
        "models.downloadedOk": "下载成功",
        "models.retrying": "重试中...",
        "models.downloadedLabel": "已下载",
        "models.clickDetails": "点击查看模型详情",
        "models.openFolder": "打开下载目录",
        "models.clickCopy": "点击复制路径",
        "models.urlHint": "粘贴 HuggingFace 仓库 ID 或 URL 直接下载。",
        "models.savedTo": "已保存至：%@",
        "models.searchPlaceholder": "搜索 HuggingFace 模型...",
        "models.urlPlaceholder": "mlx-community/model-name 或 https://huggingface.co/...",
        "models.tags": "标签",
        "models.specifications": "规格",
        "models.architecture": "架构",
        "models.modelType": "模型类型",
        "models.license": "许可证",
        "models.language": "语言",
        "models.family": "系列",
        "models.type": "类型",
        "models.size": "大小",
        "models.downloadSize": "下载大小",
        "models.diskUsage": "磁盘占用",
        "models.files": "文件（%d）",
        "models.unknown": "未知",
        "models.filesCompleted": "已完成 %d/%d 个文件",
        "models.apiKeyRequired": "需要 API 密钥",
        "models.apiKeyMessage": "管理 API 需要 API 密钥才能启用模型搜索。已自动生成密钥。",
        "models.apiKeyLabel": "API 密钥：",
        "models.saveRestart": "保存并重启",
        "models.apiKeyPlaceholder": "sk-novamlx-...",
        "models.invalidUrl": "无效 URL",
        "models.searchFailed": "搜索失败（HTTP %d）",
        "models.noResults": "未找到「%@」的相关结果",
        "models.unexpectedFormat": "响应格式异常",
        "models.searchFailedMsg": "搜索失败：%@",
        "models.invalidHfUrl": "无效的 HuggingFace URL",
        "models.invalidUrlMsg": "无效 URL，格式应为：https://huggingface.co/owner/repo",
        "models.saveFailed": "保存 API 密钥失败：%@",
        "models.gb": "GB",
        "models.mb": "MB",
        "models.cloudModels": "云端模型",
        "models.noCloudModels": "没有可用的云端模型",
        "models.noCloudModelsSub": "连接后远程模型将显示在此处",

        "chat.model": "模型",
        "chat.noModels": "未加载模型",
        "chat.clear": "清空",
        "chat.toggleParams": "切换参数设置",
        "chat.rawOutput": "原始模型输出查看器 — 不适用于日常聊天。",
        "chat.webChat": "网页聊天",
        "chat.temperature": "温度",
        "chat.topP": "Top P",
        "chat.topK": "Top K",
        "chat.minP": "Min P",
        "chat.maxTokens": "最大 Token 数",
        "chat.repeatPenalty": "重复惩罚",
        "chat.resetDefault": "恢复默认",
        "chat.startConversation": "开始对话",
        "chat.selectModel": "在上方选择模型，在下方输入消息。",
        "chat.you": "你",
        "chat.assistant": "助手",
        "chat.typePlaceholder": "输入消息...",
        "chat.noResponse": "（无回复）",
        "chat.error": "错误：%@",
        "chat.thinking": "思考过程",

        "settings.server": "服务器",
        "settings.cli": "命令行工具",
        "settings.turboQuant": "KV 量化（TurboQuant）",
        "settings.sessions": "会话",
        "settings.about": "关于",
        "settings.editConfig": "编辑配置",
        "settings.openChat": "在浏览器中打开聊天",
        "settings.openDashboard": "打开控制台",
        "settings.openConfig": "打开配置文件",
        "settings.language": "语言",
        "settings.inferenceApi": "推理 API",
        "settings.adminApi": "管理 API",
        "settings.webChat": "网页聊天",
        "settings.adminDashboard": "管理控制台",
        "settings.configFile": "配置文件",
        "settings.version": "版本",
        "settings.build": "构建",
        "settings.license": "许可证",
        "settings.platform": "平台",
        "settings.serverConfig": "服务器配置",
        "settings.host": "主机",
        "settings.port": "端口",
        "settings.adminPort": "管理端口",
        "settings.maxConcurrent": "最大并发",
        "settings.timeout": "超时（秒）",
        "settings.maxBody": "最大请求体（MB）",
        "settings.defaultModel": "默认模型",
        "settings.apiKeys": "API 密钥（每行一个）",
        "settings.clickCopy": "点击复制路径",
        "settings.hostPlaceholder": "127.0.0.1",
        "settings.modelPlaceholder": "例如 mlx-community/Qwen3-35B-4bit",
        "settings.installCli": "安装 `nova` 命令行工具到 PATH",
        "settings.installed": "已安装",
        "settings.alreadyInstalled": "已安装",
        "settings.cliNotFound": "应用包中未找到 CLI 二进制文件",
        "settings.cliInstallSuccess": "安装完成！请将 ~/.local/bin 添加到 PATH。",
        "settings.turboQuantDesc": "压缩 KV 缓存以减少 GPU 内存占用。查看状态页 GPU 指标了解效果。",
        "settings.loadModel": "加载模型以配置 KV 量化。",
        "settings.noSessions": "无活跃会话",
        "settings.off": "关闭",
        "settings.bit8": "8 位",
        "settings.bit4": "4 位",
        "settings.bit2": "2 位",
        "settings.portError": "错误：端口必须在 1-65535 之间",
        "settings.adminPortError": "错误：管理端口必须在 1-65535 之间",
        "settings.portConflict": "错误：端口和管理端口不能相同",
        "settings.concurrentError": "错误：最大并发数必须大于 0",
        "settings.savedRestart": "已保存！请重启应用以使更改生效。",
        "settings.systemDefault": "跟随系统",
        "settings.licenseValue": "Apache 2.0",
        "settings.refresh": "刷新",
        "settings.clearAll": "全部清除",
        "settings.resetCurrent": "重置为当前值",
        "settings.saveToDisk": "保存到磁盘",
        "settings.save": "保存",
        "settings.cancel": "取消",
        "settings.reset": "重置",
        "settings.memoryLimit": "内存限制",
        "settings.memoryLimitAuto": "自动",
        "settings.memoryLimitPercent": "内存百分比",
        "settings.memoryLimitFixed": "固定值",
        "settings.memoryLimitAutoDesc": "为系统预留 max(4GB, 20% 内存)，上限 8GB。剩余全部分配给 NovaMLX。",
        "settings.memoryLimitPercentLabel": "百分比",
        "settings.memoryLimitValueLabel": "数值",
        "settings.memoryLimitGB": "GB",
        "settings.memoryLimitMB": "MB",

        "agents.integrations": "智能体集成",
        "agents.configLabel": "配置",
        "agents.description": "将智能体工具连接到 NovaMLX 作为推理后端。NovaMLX 提供 OpenAI 兼容的 API 供这些智能体直接使用。",
        "agents.serverRunning": "NovaMLX 服务器运行中：%@",
        "agents.serverNotRunning": "NovaMLX 服务器未运行 — 智能体无法连接",
        "agents.installed": "已安装",
        "agents.notFound": "未找到",
        "agents.refreshStatus": "刷新智能体状态",
        "agents.checkInstalled": "检查已安装的智能体",
        "agents.launch": "启动",
        "agents.install": "安装",
        "agents.copyConfig": "复制配置",
        "agents.configCopied": "%@：配置已复制到剪贴板",
        "agents.launched": "%@：已启动",
        "agents.launchError": "%@：%@",
        "agents.openclaw": "OpenClaw",
        "agents.hermes": "Hermes Agent",
        "agents.opencode": "OpenCode",
        "agents.openclawDesc": "开源 AI 智能体框架，支持插件系统和工具调用",
        "agents.hermesDesc": "自主 AI 智能体，支持多步推理和工具执行",
        "agents.opencodeDesc": "终端 AI 编程助手，支持代码编辑",

        "dashboard.loadedModels": "已加载模型",
        "dashboard.noModelsLoaded": "未加载模型",
        "dashboard.availableModels": "可用模型",
        "dashboard.noDownloadedModels": "未找到已下载的模型",
        "dashboard.system": "系统",
        "dashboard.used": "已用",
        "dashboard.usage": "使用率",
        "dashboard.session": "会话",
        "dashboard.cores": "核心",
        "dashboard.load": "加载",

        "menuBar.openWindow": "打开窗口",
        "menuBar.quit": "退出",

        "menu.noModels": "未加载模型",
        "menu.downloadedCount": "已下载：%d 个模型",
        "menu.diskUsage": "磁盘占用：%@",
    ]

    // MARK: - Traditional Chinese (Hong Kong)

    private static let zhHantHK: [String: String] = [
        "app.status": "狀態",
        "app.models": "模型",
        "app.chat": "Playground",
        "app.agents": "智能體",
        "app.settings": "設定",
        "app.running": "運行中",
        "app.stopped": "已停止",
        "app.modelsLoaded": "已載入 %d 個模型",
        "app.nova": "Nova",
        "app.mlx": "MLX",
        "app.novamlx": "NovaMLX",

        "status.serverOnline": "伺服器在線",
        "status.serverOffline": "伺服器離線",
        "status.tokensPerSec": "token/秒",
        "status.peakTokensPerSec": "峰值 tok/s",
        "status.realtimeInferenceSpeed": "實時推理速度",
        "status.noActivity": "暫無推理活動",
        "status.time": "時間",
        "status.tokPerSec": "token/秒",
        "status.cpu": "CPU",
        "status.memory": "記憶體",
        "status.gpu": "GPU",
        "status.uptime": "運行時間",
        "status.requests": "請求數",
        "status.models": "模型",
        "status.disk": "磁碟",
        "status.totalTokens": "總 Token 數",
        "status.active": "活躍",
        "status.loaded": "已載入",
        "status.device": "裝置",
        "status.chip": "晶片",
        "status.gpuCores": "GPU 核心數",
        "status.cpuCores": "CPU 核心數",
        "status.activeModels": "活躍模型",
        "status.noModelsLoaded": "尚未載入模型。前往「模型」頁面下載並載入。",
        "status.ready": "就緒",
        "status.kv": "KV",
        "status.hour": "時",
        "status.minute": "分",
        "status.million": "M",
        "status.thousand": "K",

        "models.myModels": "我的模型",
        "models.downloads": "下載",
        "models.deleteConfirm": "刪除模型？",
        "models.deleteMessage": "將永久刪除「%@」，此操作不可撤銷。",
        "models.downloading": "下載中",
        "models.completed": "已完成",
        "models.noDownloads": "暫無下載",
        "models.noDownloadsSub": "搜尋模型或貼上 URL 開始下載。",
        "models.noModelsLoaded": "未載入模型",
        "models.noModelsLoadedSub": "載入已下載的模型以開始使用。",
        "models.noInactiveModels": "無未啟用模型",
        "models.noInactiveModelsSub": "前往瀏覽頁面搜尋並下載模型。",
        "models.searchResults": "搜尋結果",
        "models.manualDownload": "手動下載",
        "models.search": "搜尋",
        "models.download": "下載",
        "models.downloaded": "已下載",
        "models.resume": "繼續",
        "models.cancel": "取消",
        "models.delete": "刪除",
        "models.retry": "重試",
        "models.unload": "卸載",
        "models.load": "載入",
        "models.close": "關閉",
        "models.loading": "載入中...",
        "models.downloadedOk": "下載成功",
        "models.retrying": "重試中...",
        "models.downloadedLabel": "已下載",
        "models.clickDetails": "點擊查看模型詳情",
        "models.openFolder": "開啟下載資料夾",
        "models.clickCopy": "點擊複製路徑",
        "models.urlHint": "貼上 HuggingFace 倉庫 ID 或 URL 直接下載。",
        "models.savedTo": "已儲存至：%@",
        "models.searchPlaceholder": "搜尋 HuggingFace 模型...",
        "models.urlPlaceholder": "mlx-community/model-name 或 https://huggingface.co/...",
        "models.tags": "標籤",
        "models.specifications": "規格",
        "models.architecture": "架構",
        "models.modelType": "模型類型",
        "models.license": "授權",
        "models.language": "語言",
        "models.family": "系列",
        "models.type": "類型",
        "models.size": "大小",
        "models.downloadSize": "下載大小",
        "models.diskUsage": "磁碟佔用",
        "models.files": "檔案（%d）",
        "models.unknown": "未知",
        "models.filesCompleted": "已完成 %d/%d 個檔案",
        "models.apiKeyRequired": "需要 API 金鑰",
        "models.apiKeyMessage": "管理 API 需要 API 金鑰才能啟用模型搜尋。已自動產生金鑰。",
        "models.apiKeyLabel": "API 金鑰：",
        "models.saveRestart": "儲存並重啟",
        "models.apiKeyPlaceholder": "sk-novamlx-...",
        "models.invalidUrl": "無效 URL",
        "models.searchFailed": "搜尋失敗（HTTP %d）",
        "models.noResults": "未找到「%@」的相關結果",
        "models.unexpectedFormat": "回應格式異常",
        "models.searchFailedMsg": "搜尋失敗：%@",
        "models.invalidHfUrl": "無效的 HuggingFace URL",
        "models.invalidUrlMsg": "無效 URL，格式應為：https://huggingface.co/owner/repo",
        "models.saveFailed": "儲存 API 金鑰失敗：%@",
        "models.gb": "GB",
        "models.mb": "MB",
        "models.cloudModels": "雲端模型",
        "models.noCloudModels": "無可用雲端模型",
        "models.noCloudModelsSub": "連線後遠端模型將顯示在此",

        "chat.model": "模型",
        "chat.noModels": "未載入模型",
        "chat.clear": "清空",
        "chat.toggleParams": "切換參數設定",
        "chat.rawOutput": "原始模型輸出檢視器 — 不適用於日常聊天。",
        "chat.webChat": "網頁聊天",
        "chat.temperature": "溫度",
        "chat.topP": "Top P",
        "chat.topK": "Top K",
        "chat.minP": "Min P",
        "chat.maxTokens": "最大 Token 數",
        "chat.repeatPenalty": "重複懲罰",
        "chat.resetDefault": "恢復預設",
        "chat.startConversation": "開始對話",
        "chat.selectModel": "在上方選擇模型，在下方輸入訊息。",
        "chat.you": "你",
        "chat.assistant": "助手",
        "chat.typePlaceholder": "輸入訊息...",
        "chat.noResponse": "（無回覆）",
        "chat.error": "錯誤：%@",
        "chat.thinking": "思考過程",

        "settings.server": "伺服器",
        "settings.cli": "命令行工具",
        "settings.turboQuant": "KV 量化（TurboQuant）",
        "settings.sessions": "工作階段",
        "settings.about": "關於",
        "settings.editConfig": "編輯設定",
        "settings.openChat": "在瀏覽器中開啟聊天",
        "settings.openDashboard": "開啟控制台",
        "settings.openConfig": "開啟設定檔",
        "settings.language": "語言",
        "settings.inferenceApi": "推理 API",
        "settings.adminApi": "管理 API",
        "settings.webChat": "網頁聊天",
        "settings.adminDashboard": "管理控制台",
        "settings.configFile": "設定檔",
        "settings.version": "版本",
        "settings.build": "建置",
        "settings.license": "授權",
        "settings.platform": "平台",
        "settings.serverConfig": "伺服器設定",
        "settings.host": "主機",
        "settings.port": "連接埠",
        "settings.adminPort": "管理連接埠",
        "settings.maxConcurrent": "最大並行",
        "settings.timeout": "逾時（秒）",
        "settings.maxBody": "最大請求主體（MB）",
        "settings.defaultModel": "預設模型",
        "settings.apiKeys": "API 金鑰（每行一個）",
        "settings.clickCopy": "點擊複製路徑",
        "settings.hostPlaceholder": "127.0.0.1",
        "settings.modelPlaceholder": "例如 mlx-community/Qwen3-35B-4bit",
        "settings.installCli": "安裝 `nova` 命令行工具到 PATH",
        "settings.installed": "已安裝",
        "settings.alreadyInstalled": "已安裝",
        "settings.cliNotFound": "應用程式中未找到 CLI 二進位檔",
        "settings.cliInstallSuccess": "安裝完成！請將 ~/.local/bin 加入 PATH。",
        "settings.turboQuantDesc": "壓縮 KV 快取以減少 GPU 記憶體佔用。查看狀態頁 GPU 指標了解效果。",
        "settings.loadModel": "載入模型以設定 KV 量化。",
        "settings.noSessions": "無活躍工作階段",
        "settings.off": "關閉",
        "settings.bit8": "8 位元",
        "settings.bit4": "4 位元",
        "settings.bit2": "2 位元",
        "settings.portError": "錯誤：連接埠必須在 1-65535 之間",
        "settings.adminPortError": "錯誤：管理連接埠必須在 1-65535 之間",
        "settings.portConflict": "錯誤：連接埠和管理連接埠不能相同",
        "settings.concurrentError": "錯誤：最大並行數必須大於 0",
        "settings.savedRestart": "已儲存！請重啟應用程式以使更改生效。",
        "settings.systemDefault": "跟隨系統",
        "settings.licenseValue": "Apache 2.0",
        "settings.refresh": "重新整理",
        "settings.clearAll": "全部清除",
        "settings.resetCurrent": "重設為當前值",
        "settings.saveToDisk": "儲存到磁碟",
        "settings.save": "儲存",
        "settings.cancel": "取消",
        "settings.reset": "重設",
        "settings.memoryLimit": "記憶體限制",
        "settings.memoryLimitAuto": "自動",
        "settings.memoryLimitPercent": "記憶體百分比",
        "settings.memoryLimitFixed": "固定值",
        "settings.memoryLimitAutoDesc": "為系統預留 max(4GB, 20% 記憶體)，上限 8GB。剩餘全部分配給 NovaMLX。",
        "settings.memoryLimitPercentLabel": "百分比",
        "settings.memoryLimitValueLabel": "數值",
        "settings.memoryLimitGB": "GB",
        "settings.memoryLimitMB": "MB",

        "agents.integrations": "智能體整合",
        "agents.configLabel": "設定",
        "agents.description": "將智能體工具連接到 NovaMLX 作為推理後端。NovaMLX 提供 OpenAI 相容的 API 供這些智能體直接使用。",
        "agents.serverRunning": "NovaMLX 伺服器運行中：%@",
        "agents.serverNotRunning": "NovaMLX 伺服器未運行 — 智能體無法連接",
        "agents.installed": "已安裝",
        "agents.notFound": "未找到",
        "agents.refreshStatus": "重新整理智能體狀態",
        "agents.checkInstalled": "檢查已安裝的智能體",
        "agents.launch": "啟動",
        "agents.install": "安裝",
        "agents.copyConfig": "複製設定",
        "agents.configCopied": "%@：設定已複製到剪貼簿",
        "agents.launched": "%@：已啟動",
        "agents.launchError": "%@：%@",
        "agents.openclaw": "OpenClaw",
        "agents.hermes": "Hermes Agent",
        "agents.opencode": "OpenCode",
        "agents.openclawDesc": "開源 AI 智能體框架，支援插件系統和工具呼叫",
        "agents.hermesDesc": "自主 AI 智能體，支援多步推理和工具執行",
        "agents.opencodeDesc": "終端 AI 程式設計助手，支援程式碼編輯",

        "dashboard.loadedModels": "已載入模型",
        "dashboard.noModelsLoaded": "未載入模型",
        "dashboard.availableModels": "可用模型",
        "dashboard.noDownloadedModels": "未找到已下載的模型",
        "dashboard.system": "系統",
        "dashboard.used": "已用",
        "dashboard.usage": "使用率",
        "dashboard.session": "工作階段",
        "dashboard.cores": "核心",
        "dashboard.load": "載入",

        "menuBar.openWindow": "開啟視窗",
        "menuBar.quit": "結束",

        "menu.noModels": "未載入模型",
        "menu.downloadedCount": "已下載：%d 個模型",
        "menu.diskUsage": "磁碟佔用：%@",
    ]

    // MARK: - Traditional Chinese (Taiwan)

    private static let zhHantTW: [String: String] = [
        "app.status": "狀態",
        "app.models": "模型",
        "app.chat": "Playground",
        "app.agents": "智慧代理",
        "app.settings": "設定",
        "app.running": "執行中",
        "app.stopped": "已停止",
        "app.modelsLoaded": "已載入 %d 個模型",
        "app.nova": "Nova",
        "app.mlx": "MLX",
        "app.novamlx": "NovaMLX",

        "status.serverOnline": "伺服器上線",
        "status.serverOffline": "伺服器離線",
        "status.tokensPerSec": "token/秒",
        "status.peakTokensPerSec": "峰值 tok/s",
        "status.realtimeInferenceSpeed": "即時推論速度",
        "status.noActivity": "尚無推論活動",
        "status.time": "時間",
        "status.tokPerSec": "token/秒",
        "status.cpu": "CPU",
        "status.memory": "記憶體",
        "status.gpu": "GPU",
        "status.uptime": "執行時間",
        "status.requests": "請求數",
        "status.models": "模型",
        "status.disk": "磁碟",
        "status.totalTokens": "總 Token 數",
        "status.active": "活躍",
        "status.loaded": "已載入",
        "status.device": "裝置",
        "status.chip": "晶片",
        "status.gpuCores": "GPU 核心數",
        "status.cpuCores": "CPU 核心數",
        "status.activeModels": "活躍模型",
        "status.noModelsLoaded": "尚未載入模型。前往「模型」頁面下載並載入。",
        "status.ready": "就緒",
        "status.kv": "KV",
        "status.hour": "時",
        "status.minute": "分",
        "status.million": "M",
        "status.thousand": "K",

        "models.myModels": "我的模型",
        "models.downloads": "下載",
        "models.deleteConfirm": "刪除模型？",
        "models.deleteMessage": "將永久刪除「%@」，此操作不可復原。",
        "models.downloading": "下載中",
        "models.completed": "已完成",
        "models.noDownloads": "尚無下載",
        "models.noDownloadsSub": "搜尋模型或貼上 URL 開始下載。",
        "models.noModelsLoaded": "未載入模型",
        "models.noModelsLoadedSub": "載入已下載的模型以開始使用。",
        "models.noInactiveModels": "無未啟用模型",
        "models.noInactiveModelsSub": "前往瀏覽頁面搜尋並下載模型。",
        "models.searchResults": "搜尋結果",
        "models.manualDownload": "手動下載",
        "models.search": "搜尋",
        "models.download": "下載",
        "models.downloaded": "已下載",
        "models.resume": "繼續",
        "models.cancel": "取消",
        "models.delete": "刪除",
        "models.retry": "重試",
        "models.unload": "卸載",
        "models.load": "載入",
        "models.close": "關閉",
        "models.loading": "載入中...",
        "models.downloadedOk": "下載成功",
        "models.retrying": "重試中...",
        "models.downloadedLabel": "已下載",
        "models.clickDetails": "點按查看模型詳細資訊",
        "models.openFolder": "開啟下載檔案夾",
        "models.clickCopy": "點按複製路徑",
        "models.urlHint": "貼上 HuggingFace 儲存庫 ID 或 URL 直接下載。",
        "models.savedTo": "已儲存至：%@",
        "models.searchPlaceholder": "搜尋 HuggingFace 模型...",
        "models.urlPlaceholder": "mlx-community/model-name 或 https://huggingface.co/...",
        "models.tags": "標籤",
        "models.specifications": "規格",
        "models.architecture": "架構",
        "models.modelType": "模型類型",
        "models.license": "授權",
        "models.language": "語言",
        "models.family": "系列",
        "models.type": "類型",
        "models.size": "大小",
        "models.downloadSize": "下載大小",
        "models.diskUsage": "磁碟用量",
        "models.files": "檔案（%d）",
        "models.unknown": "未知",
        "models.filesCompleted": "已完成 %d/%d 個檔案",
        "models.apiKeyRequired": "需要 API 金鑰",
        "models.apiKeyMessage": "管理 API 需要 API 金鑰才能啟用模型搜尋。已自動產生金鑰。",
        "models.apiKeyLabel": "API 金鑰：",
        "models.saveRestart": "儲存並重新啟動",
        "models.apiKeyPlaceholder": "sk-novamlx-...",
        "models.invalidUrl": "無效的 URL",
        "models.searchFailed": "搜尋失敗（HTTP %d）",
        "models.noResults": "找不到「%@」的相關結果",
        "models.unexpectedFormat": "回應格式異常",
        "models.searchFailedMsg": "搜尋失敗：%@",
        "models.invalidHfUrl": "無效的 HuggingFace URL",
        "models.invalidUrlMsg": "無效的 URL，格式應為：https://huggingface.co/owner/repo",
        "models.saveFailed": "儲存 API 金鑰失敗：%@",
        "models.gb": "GB",
        "models.mb": "MB",
        "models.cloudModels": "雲端模型",
        "models.noCloudModels": "無可用雲端模型",
        "models.noCloudModelsSub": "連線後遠端模型將顯示在此",

        "chat.model": "模型",
        "chat.noModels": "未載入模型",
        "chat.clear": "清空",
        "chat.toggleParams": "切換參數設定",
        "chat.rawOutput": "原始模型輸出檢視器 — 不適用於日常聊天。",
        "chat.webChat": "網頁聊天",
        "chat.temperature": "溫度",
        "chat.topP": "Top P",
        "chat.topK": "Top K",
        "chat.minP": "Min P",
        "chat.maxTokens": "最大 Token 數",
        "chat.repeatPenalty": "重複懲罰",
        "chat.resetDefault": "還原預設值",
        "chat.startConversation": "開始對話",
        "chat.selectModel": "在上方選擇模型，在下方輸入訊息。",
        "chat.you": "您",
        "chat.assistant": "助手",
        "chat.typePlaceholder": "輸入訊息...",
        "chat.noResponse": "（無回應）",
        "chat.error": "錯誤：%@",
        "chat.thinking": "思考過程",

        "settings.server": "伺服器",
        "settings.cli": "命令列工具",
        "settings.turboQuant": "KV 量化（TurboQuant）",
        "settings.sessions": "作業階段",
        "settings.about": "關於",
        "settings.editConfig": "編輯設定",
        "settings.openChat": "在瀏覽器中開啟聊天",
        "settings.openDashboard": "開啟控制台",
        "settings.openConfig": "開啟設定檔",
        "settings.language": "語言",
        "settings.inferenceApi": "推論 API",
        "settings.adminApi": "管理 API",
        "settings.webChat": "網頁聊天",
        "settings.adminDashboard": "管理控制台",
        "settings.configFile": "設定檔",
        "settings.version": "版本",
        "settings.build": "建置",
        "settings.license": "授權",
        "settings.platform": "平台",
        "settings.serverConfig": "伺服器設定",
        "settings.host": "主機",
        "settings.port": "連接埠",
        "settings.adminPort": "管理連接埠",
        "settings.maxConcurrent": "最大並行",
        "settings.timeout": "逾時（秒）",
        "settings.maxBody": "最大請求主體（MB）",
        "settings.defaultModel": "預設模型",
        "settings.apiKeys": "API 金鑰（每行一個）",
        "settings.clickCopy": "點按複製路徑",
        "settings.hostPlaceholder": "127.0.0.1",
        "settings.modelPlaceholder": "例如 mlx-community/Qwen3-35B-4bit",
        "settings.installCli": "安裝 `nova` 命令列工具到 PATH",
        "settings.installed": "已安裝",
        "settings.alreadyInstalled": "已安裝",
        "settings.cliNotFound": "應用程式中找不到 CLI 二進位檔",
        "settings.cliInstallSuccess": "安裝完成！請將 ~/.local/bin 加入 PATH。",
        "settings.turboQuantDesc": "壓縮 KV 快取以減少 GPU 記憶體佔用。檢視狀態頁 GPU 指標了解效果。",
        "settings.loadModel": "載入模型以設定 KV 量化。",
        "settings.noSessions": "無活躍作業階段",
        "settings.off": "關閉",
        "settings.bit8": "8 位元",
        "settings.bit4": "4 位元",
        "settings.bit2": "2 位元",
        "settings.portError": "錯誤：連接埠必須在 1-65535 之間",
        "settings.adminPortError": "錯誤：管理連接埠必須在 1-65535 之間",
        "settings.portConflict": "錯誤：連接埠和管理連接埠不能相同",
        "settings.concurrentError": "錯誤：最大並行數必須大於 0",
        "settings.savedRestart": "已儲存！請重新啟動應用程式以套用更改。",
        "settings.systemDefault": "依照系統",
        "settings.licenseValue": "Apache 2.0",
        "settings.refresh": "重新整理",
        "settings.clearAll": "全部清除",
        "settings.resetCurrent": "重設為當前值",
        "settings.saveToDisk": "儲存到磁碟",
        "settings.save": "儲存",
        "settings.cancel": "取消",
        "settings.reset": "重設",
        "settings.memoryLimit": "記憶體限制",
        "settings.memoryLimitAuto": "自動",
        "settings.memoryLimitPercent": "記憶體百分比",
        "settings.memoryLimitFixed": "固定值",
        "settings.memoryLimitAutoDesc": "為系統預留 max(4GB, 20% 記憶體)，上限 8GB。剩餘全部分配給 NovaMLX。",
        "settings.memoryLimitPercentLabel": "百分比",
        "settings.memoryLimitValueLabel": "數值",
        "settings.memoryLimitGB": "GB",
        "settings.memoryLimitMB": "MB",

        "agents.integrations": "智慧代理整合",
        "agents.configLabel": "設定",
        "agents.description": "將智慧代理工具連接到 NovaMLX 作為推論後端。NovaMLX 提供 OpenAI 相容的 API 供這些代理直接使用。",
        "agents.serverRunning": "NovaMLX 伺服器執行中：%@",
        "agents.serverNotRunning": "NovaMLX 伺服器未執行 — 智慧代理無法連線",
        "agents.installed": "已安裝",
        "agents.notFound": "找不到",
        "agents.refreshStatus": "重新整理代理狀態",
        "agents.checkInstalled": "檢查已安裝的代理",
        "agents.launch": "啟動",
        "agents.install": "安裝",
        "agents.copyConfig": "拷貝設定",
        "agents.configCopied": "%@：設定已拷貝至剪貼板",
        "agents.launched": "%@：已啟動",
        "agents.launchError": "%@：%@",
        "agents.openclaw": "OpenClaw",
        "agents.hermes": "Hermes Agent",
        "agents.opencode": "OpenCode",
        "agents.openclawDesc": "開放原始碼 AI 智慧代理框架，支援延伸功能系統和工具使用",
        "agents.hermesDesc": "自主 AI 智慧代理，支援多步驟推論和工具執行",
        "agents.opencodeDesc": "終端機 AI 程式設計助手，支援程式碼編輯",

        "dashboard.loadedModels": "已載入模型",
        "dashboard.noModelsLoaded": "未載入模型",
        "dashboard.availableModels": "可用模型",
        "dashboard.noDownloadedModels": "找不到已下載的模型",
        "dashboard.system": "系統",
        "dashboard.used": "已用",
        "dashboard.usage": "使用率",
        "dashboard.session": "作業階段",
        "dashboard.cores": "核心",
        "dashboard.load": "載入",

        "menuBar.openWindow": "開啟視窗",
        "menuBar.quit": "結束",

        "menu.noModels": "未載入模型",
        "menu.downloadedCount": "已下載：%d 個模型",
        "menu.diskUsage": "磁碟用量：%@",
    ]

    // MARK: - Japanese

    private static let ja: [String: String] = [
        "app.status": "ステータス",
        "app.models": "モデル",
        "app.chat": "Playground",
        "app.agents": "エージェント",
        "app.settings": "設定",
        "app.running": "実行中",
        "app.stopped": "停止",
        "app.modelsLoaded": "%d モデル読込済",
        "app.nova": "Nova",
        "app.mlx": "MLX",
        "app.novamlx": "NovaMLX",

        "status.serverOnline": "サーバーオンライン",
        "status.serverOffline": "サーバーオフライン",
        "status.tokensPerSec": "token/秒",
        "status.peakTokensPerSec": "ピーク tok/s",
        "status.realtimeInferenceSpeed": "リアルタイム推論速度",
        "status.noActivity": "推論アクティビティなし",
        "status.time": "時間",
        "status.tokPerSec": "token/秒",
        "status.cpu": "CPU",
        "status.memory": "メモリ",
        "status.gpu": "GPU",
        "status.uptime": "稼働時間",
        "status.requests": "リクエスト",
        "status.models": "モデル",
        "status.disk": "ディスク",
        "status.totalTokens": "合計トークン数",
        "status.active": "アクティブ",
        "status.loaded": "読込済",
        "status.device": "デバイス",
        "status.chip": "チップ",
        "status.gpuCores": "GPUコア数",
        "status.cpuCores": "CPUコア数",
        "status.activeModels": "アクティブモデル",
        "status.noModelsLoaded": "モデルが読み込まれていません。「モデル」ページからダウンロードして読み込んでください。",
        "status.ready": "準備完了",
        "status.kv": "KV",
        "status.hour": "時間",
        "status.minute": "分",
        "status.million": "M",
        "status.thousand": "K",

        "models.myModels": "マイモデル",
        "models.downloads": "ダウンロード",
        "models.deleteConfirm": "モデルを削除しますか？",
        "models.deleteMessage": "「%@」をディスクから完全に削除します。この操作は取り消せません。",
        "models.downloading": "ダウンロード中",
        "models.completed": "完了",
        "models.noDownloads": "ダウンロードなし",
        "models.noDownloadsSub": "モデルを検索するか、URLを貼り付けてダウンロードを開始してください。",
        "models.noModelsLoaded": "モデル未読込",
        "models.noModelsLoadedSub": "ダウンロード済みのモデルを読み込んで使用を開始してください。",
        "models.noInactiveModels": "非アクティブなモデルなし",
        "models.noInactiveModelsSub": "ブラウズページでモデルを検索・ダウンロードしてください。",
        "models.searchResults": "検索結果",
        "models.manualDownload": "手動ダウンロード",
        "models.search": "検索",
        "models.download": "ダウンロード",
        "models.downloaded": "ダウンロード済",
        "models.resume": "再開",
        "models.cancel": "キャンセル",
        "models.delete": "削除",
        "models.retry": "再試行",
        "models.unload": "アンロード",
        "models.load": "読込",
        "models.close": "閉じる",
        "models.loading": "読込中...",
        "models.downloadedOk": "ダウンロード完了",
        "models.retrying": "再試行中...",
        "models.downloadedLabel": "ダウンロード済",
        "models.clickDetails": "クリックしてモデル詳細を表示",
        "models.openFolder": "ダウンロードフォルダを開く",
        "models.clickCopy": "クリックしてパスをコピー",
        "models.urlHint": "HuggingFaceリポジトリIDまたはURLを貼り付けて直接ダウンロード。",
        "models.savedTo": "保存先：%@",
        "models.searchPlaceholder": "HuggingFaceモデルを検索...",
        "models.urlPlaceholder": "mlx-community/model-name または https://huggingface.co/...",
        "models.tags": "タグ",
        "models.specifications": "仕様",
        "models.architecture": "アーキテクチャ",
        "models.modelType": "モデルタイプ",
        "models.license": "ライセンス",
        "models.language": "言語",
        "models.family": "ファミリー",
        "models.type": "タイプ",
        "models.size": "サイズ",
        "models.downloadSize": "ダウンロードサイズ",
        "models.diskUsage": "ディスク使用量",
        "models.files": "ファイル（%d）",
        "models.unknown": "不明",
        "models.filesCompleted": "%d/%d ファイル完了",
        "models.apiKeyRequired": "APIキーが必要です",
        "models.apiKeyMessage": "管理APIを使用するにはAPIキーが必要です。以下に自動生成されたキーが表示されています。",
        "models.apiKeyLabel": "APIキー：",
        "models.saveRestart": "保存して再起動",
        "models.apiKeyPlaceholder": "sk-novamlx-...",
        "models.invalidUrl": "無効なURL",
        "models.searchFailed": "検索失敗（HTTP %d）",
        "models.noResults": "「%@」の検索結果が見つかりません",
        "models.unexpectedFormat": "予期しないレスポンス形式",
        "models.searchFailedMsg": "検索失敗：%@",
        "models.invalidHfUrl": "無効なHuggingFace URL",
        "models.invalidUrlMsg": "無効なURL。形式：https://huggingface.co/owner/repo",
        "models.saveFailed": "APIキーの保存に失敗：%@",
        "models.gb": "GB",
        "models.mb": "MB",
        "models.cloudModels": "クラウドモデル",
        "models.noCloudModels": "クラウドモデルなし",
        "models.noCloudModelsSub": "接続時にリモートモデルが表示されます",

        "chat.model": "モデル",
        "chat.noModels": "モデル未読込",
        "chat.clear": "クリア",
        "chat.toggleParams": "パラメータ設定の切替",
        "chat.rawOutput": "Raw model output viewer — not designed for daily chat use.",
        "chat.webChat": "Webチャット",
        "chat.temperature": "温度",
        "chat.topP": "Top P",
        "chat.topK": "Top K",
        "chat.minP": "Min P",
        "chat.maxTokens": "最大トークン数",
        "chat.repeatPenalty": "繰返ペナルティ",
        "chat.resetDefault": "デフォルトに戻す",
        "chat.startConversation": "会話を始める",
        "chat.selectModel": "上のモデルを選択し、下にメッセージを入力してください。",
        "chat.you": "あなた",
        "chat.assistant": "アシスタント",
        "chat.typePlaceholder": "メッセージを入力...",
        "chat.noResponse": "（応答なし）",
        "chat.error": "エラー：%@",
        "chat.thinking": "思考",

        "settings.server": "サーバー",
        "settings.cli": "コマンドラインツール",
        "settings.turboQuant": "KV量子化（TurboQuant）",
        "settings.sessions": "セッション",
        "settings.about": "概要",
        "settings.editConfig": "設定を編集",
        "settings.openChat": "ブラウザでチャットを開く",
        "settings.openDashboard": "ダッシュボードを開く",
        "settings.openConfig": "設定ファイルを開く",
        "settings.language": "言語",
        "settings.inferenceApi": "推論API",
        "settings.adminApi": "管理API",
        "settings.webChat": "Webチャット",
        "settings.adminDashboard": "管理ダッシュボード",
        "settings.configFile": "設定ファイル",
        "settings.version": "バージョン",
        "settings.build": "ビルド",
        "settings.license": "ライセンス",
        "settings.platform": "プラットフォーム",
        "settings.serverConfig": "サーバー設定",
        "settings.host": "ホスト",
        "settings.port": "ポート",
        "settings.adminPort": "管理ポート",
        "settings.maxConcurrent": "最大同時接続",
        "settings.timeout": "タイムアウト（秒）",
        "settings.maxBody": "最大ボディ（MB）",
        "settings.defaultModel": "デフォルトモデル",
        "settings.apiKeys": "APIキー（1行に1つ）",
        "settings.clickCopy": "クリックしてパスをコピー",
        "settings.hostPlaceholder": "127.0.0.1",
        "settings.modelPlaceholder": "例：mlx-community/Qwen3-35B-4bit",
        "settings.installCli": "`nova` CLIをPATHにインストール",
        "settings.installed": "インストール済",
        "settings.alreadyInstalled": "インストール済み",
        "settings.cliNotFound": "アプリバンドルにCLIバイナリが見つかりません",
        "settings.cliInstallSuccess": "インストール完了！~/.local/binをPATHに追加してください。",
        "settings.turboQuantDesc": "KVキャッシュを圧縮してGPUメモリを削減します。ステータスページのGPU指標で効果を確認できます。",
        "settings.loadModel": "モデルを読み込んでKV量子化を設定してください。",
        "settings.noSessions": "アクティブなセッションなし",
        "settings.off": "オフ",
        "settings.bit8": "8ビット",
        "settings.bit4": "4ビット",
        "settings.bit2": "2ビット",
        "settings.portError": "エラー：ポートは1-65535の範囲で指定してください",
        "settings.adminPortError": "エラー：管理ポートは1-65535の範囲で指定してください",
        "settings.portConflict": "エラー：ポートと管理ポートは異なる値にしてください",
        "settings.concurrentError": "エラー：最大同時接続数は0より大きい値にしてください",
        "settings.savedRestart": "保存しました！変更を適用するにはアプリを再起動してください。",
        "settings.systemDefault": "システム設定",
        "settings.licenseValue": "Apache 2.0",
        "settings.refresh": "更新",
        "settings.clearAll": "全てクリア",
        "settings.resetCurrent": "現在の値にリセット",
        "settings.saveToDisk": "ディスクに保存",
        "settings.save": "保存",
        "settings.cancel": "キャンセル",
        "settings.reset": "リセット",
        "settings.memoryLimit": "メモリ制限",
        "settings.memoryLimitAuto": "自動",
        "settings.memoryLimitPercent": "RAMの%",
        "settings.memoryLimitFixed": "固定値",
        "settings.memoryLimitAutoDesc": "システム用に max(4GB, 20% RAM) を確保（上限 8GB）。残りは NovaMLX が使用。",
        "settings.memoryLimitPercentLabel": "パーセント",
        "settings.memoryLimitValueLabel": "値",
        "settings.memoryLimitGB": "GB",
        "settings.memoryLimitMB": "MB",

        "agents.integrations": "エージェント統合",
        "agents.configLabel": "設定",
        "agents.description": "エージェントツールをNovaMLXの推論バックエンドとして接続します。NovaMLXはOpenAI互換APIを提供します。",
        "agents.serverRunning": "NovaMLXサーバー実行中：%@",
        "agents.serverNotRunning": "NovaMLXサーバーが停止中 — エージェントは接続できません",
        "agents.installed": "インストール済",
        "agents.notFound": "未検出",
        "agents.refreshStatus": "エージェント状態を更新",
        "agents.checkInstalled": "インストール済みを確認",
        "agents.launch": "起動",
        "agents.install": "インストール",
        "agents.copyConfig": "設定をコピー",
        "agents.configCopied": "%@：設定をクリップボードにコピーしました",
        "agents.launched": "%@：起動しました",
        "agents.launchError": "%@：%@",
        "agents.openclaw": "OpenClaw",
        "agents.hermes": "Hermes Agent",
        "agents.opencode": "OpenCode",
        "agents.openclawDesc": "プラグインシステムとツール使用を備えたオープンソースAIエージェントフレームワーク",
        "agents.hermesDesc": "マルチステップ推論とツール実行を備えた自律AIエージェント",
        "agents.opencodeDesc": "コード編集をサポートするターミナルベースのAIプログラミングアシスタント",

        "dashboard.loadedModels": "読込済モデル",
        "dashboard.noModelsLoaded": "モデル未読込",
        "dashboard.availableModels": "利用可能なモデル",
        "dashboard.noDownloadedModels": "ダウンロード済みのモデルが見つかりません",
        "dashboard.system": "システム",
        "dashboard.used": "使用中",
        "dashboard.usage": "使用率",
        "dashboard.session": "セッション",
        "dashboard.cores": "コア",
        "dashboard.load": "読込",

        "menuBar.openWindow": "ウィンドウを開く",
        "menuBar.quit": "終了",

        "menu.noModels": "モデル未読込",
        "menu.downloadedCount": "ダウンロード済：%d モデル",
        "menu.diskUsage": "ディスク使用量：%@",
    ]

    // MARK: - Korean

    private static let ko: [String: String] = [
        "app.status": "상태",
        "app.models": "모델",
        "app.chat": "Playground",
        "app.agents": "에이전트",
        "app.settings": "설정",
        "app.running": "실행 중",
        "app.stopped": "중지됨",
        "app.modelsLoaded": "모델 %d개 로드됨",
        "app.nova": "Nova",
        "app.mlx": "MLX",
        "app.novamlx": "NovaMLX",

        "status.serverOnline": "서버 온라인",
        "status.serverOffline": "서버 오프라인",
        "status.tokensPerSec": "토큰/초",
        "status.peakTokensPerSec": "최고 tok/s",
        "status.realtimeInferenceSpeed": "실시간 추론 속도",
        "status.noActivity": "추론 활동 없음",
        "status.time": "시간",
        "status.tokPerSec": "토큰/초",
        "status.cpu": "CPU",
        "status.memory": "메모리",
        "status.gpu": "GPU",
        "status.uptime": "가동 시간",
        "status.requests": "요청",
        "status.models": "모델",
        "status.disk": "디스크",
        "status.totalTokens": "총 토큰 수",
        "status.active": "활성",
        "status.loaded": "로드됨",
        "status.device": "장치",
        "status.chip": "칩",
        "status.gpuCores": "GPU 코어 수",
        "status.cpuCores": "CPU 코어 수",
        "status.activeModels": "활성 모델",
        "status.noModelsLoaded": "로드된 모델이 없습니다. 「모델」 페이지에서 다운로드하고 로드하세요.",
        "status.ready": "준비 완료",
        "status.kv": "KV",
        "status.hour": "시간",
        "status.minute": "분",
        "status.million": "M",
        "status.thousand": "K",

        "models.myModels": "내 모델",
        "models.downloads": "다운로드",
        "models.deleteConfirm": "모델을 삭제하시겠습니까?",
        "models.deleteMessage": "「%@」을(를) 디스크에서 영구 삭제합니다. 이 작업은 되돌릴 수 없습니다.",
        "models.downloading": "다운로드 중",
        "models.completed": "완료",
        "models.noDownloads": "다운로드 없음",
        "models.noDownloadsSub": "모델을 검색하거나 URL을 붙여넣어 다운로드를 시작하세요.",
        "models.noModelsLoaded": "로드된 모델 없음",
        "models.noModelsLoadedSub": "다운로드한 모델을 로드하여 사용을 시작하세요.",
        "models.noInactiveModels": "비활성 모델 없음",
        "models.noInactiveModelsSub": "검색 페이지에서 모델을 검색하고 다운로드하세요.",
        "models.searchResults": "검색 결과",
        "models.manualDownload": "수동 다운로드",
        "models.search": "검색",
        "models.download": "다운로드",
        "models.downloaded": "다운로드됨",
        "models.resume": "재개",
        "models.cancel": "취소",
        "models.delete": "삭제",
        "models.retry": "재시도",
        "models.unload": "언로드",
        "models.load": "로드",
        "models.close": "닫기",
        "models.loading": "로딩 중...",
        "models.downloadedOk": "다운로드 완료",
        "models.retrying": "재시도 중...",
        "models.downloadedLabel": "다운로드됨",
        "models.clickDetails": "클릭하여 모델 상세 정보 보기",
        "models.openFolder": "다운로드 폴더 열기",
        "models.clickCopy": "클릭하여 경로 복사",
        "models.urlHint": "HuggingFace 리포지토리 ID 또는 URL을 붙여넣어 직접 다운로드하세요.",
        "models.savedTo": "저장 위치：%@",
        "models.searchPlaceholder": "HuggingFace 모델 검색...",
        "models.urlPlaceholder": "mlx-community/model-name 또는 https://huggingface.co/...",
        "models.tags": "태그",
        "models.specifications": "사양",
        "models.architecture": "아키텍처",
        "models.modelType": "모델 유형",
        "models.license": "라이선스",
        "models.language": "언어",
        "models.family": "패밀리",
        "models.type": "유형",
        "models.size": "크기",
        "models.downloadSize": "다운로드 크기",
        "models.diskUsage": "디스크 사용량",
        "models.files": "파일（%d）",
        "models.unknown": "알 수 없음",
        "models.filesCompleted": "%d/%d 파일 완료",
        "models.apiKeyRequired": "API 키 필요",
        "models.apiKeyMessage": "관리 API를 사용하려면 API 키가 필요합니다. 아래에 자동 생성된 키가 표시됩니다.",
        "models.apiKeyLabel": "API 키：",
        "models.saveRestart": "저장 후 재시작",
        "models.apiKeyPlaceholder": "sk-novamlx-...",
        "models.invalidUrl": "잘못된 URL",
        "models.searchFailed": "검색 실패（HTTP %d）",
        "models.noResults": "「%@」에 대한 검색 결과가 없습니다",
        "models.unexpectedFormat": "예상치 못한 응답 형식",
        "models.searchFailedMsg": "검색 실패：%@",
        "models.invalidHfUrl": "잘못된 HuggingFace URL",
        "models.invalidUrlMsg": "잘못된 URL. 형식：https://huggingface.co/owner/repo",
        "models.saveFailed": "API 키 저장 실패：%@",
        "models.gb": "GB",
        "models.mb": "MB",
        "models.cloudModels": "클라우드 모델",
        "models.noCloudModels": "사용 가능한 클라우드 모델 없음",
        "models.noCloudModelsSub": "연결 시 원격 모델이 표시됩니다",

        "chat.model": "모델",
        "chat.noModels": "로드된 모델 없음",
        "chat.clear": "지우기",
        "chat.toggleParams": "매개변수 설정 전환",
        "chat.rawOutput": "원시 모델 출력 뷰어 — 일상적인 채팅용이 아닙니다.",
        "chat.webChat": "웹 채팅",
        "chat.temperature": "온도",
        "chat.topP": "Top P",
        "chat.topK": "Top K",
        "chat.minP": "Min P",
        "chat.maxTokens": "최대 토큰 수",
        "chat.repeatPenalty": "반복 페널티",
        "chat.resetDefault": "기본값으로 복원",
        "chat.startConversation": "대화 시작",
        "chat.selectModel": "위에서 모델을 선택하고 아래에 메시지를 입력하세요.",
        "chat.you": "나",
        "chat.assistant": "어시스턴트",
        "chat.typePlaceholder": "메시지를 입력하세요...",
        "chat.noResponse": "（응답 없음）",
        "chat.error": "오류：%@",
        "chat.thinking": "생각",

        "settings.server": "서버",
        "settings.cli": "명령줄 도구",
        "settings.turboQuant": "KV 양자화（TurboQuant）",
        "settings.sessions": "세션",
        "settings.about": "정보",
        "settings.editConfig": "설정 편집",
        "settings.openChat": "브라우저에서 채팅 열기",
        "settings.openDashboard": "대시보드 열기",
        "settings.openConfig": "설정 파일 열기",
        "settings.language": "언어",
        "settings.inferenceApi": "추론 API",
        "settings.adminApi": "관리 API",
        "settings.webChat": "웹 채팅",
        "settings.adminDashboard": "관리 대시보드",
        "settings.configFile": "설정 파일",
        "settings.version": "버전",
        "settings.build": "빌드",
        "settings.license": "라이선스",
        "settings.platform": "플랫폼",
        "settings.serverConfig": "서버 설정",
        "settings.host": "호스트",
        "settings.port": "포트",
        "settings.adminPort": "관리 포트",
        "settings.maxConcurrent": "최대 동시 연결",
        "settings.timeout": "시간 초과（초）",
        "settings.maxBody": "최대 본문（MB）",
        "settings.defaultModel": "기본 모델",
        "settings.apiKeys": "API 키（줄당 하나）",
        "settings.clickCopy": "클릭하여 경로 복사",
        "settings.hostPlaceholder": "127.0.0.1",
        "settings.modelPlaceholder": "예：mlx-community/Qwen3-35B-4bit",
        "settings.installCli": "`nova` CLI를 PATH에 설치",
        "settings.installed": "설치됨",
        "settings.alreadyInstalled": "이미 설치됨",
        "settings.cliNotFound": "앱 번들에서 CLI 바이너리를 찾을 수 없습니다",
        "settings.cliInstallSuccess": "설치 완료！~/.local/bin을 PATH에 추가하세요.",
        "settings.turboQuantDesc": "KV 캐시를 압축하여 GPU 메모리를 줄입니다. 상태 페이지의 GPU 지표에서 효과를 확인하세요.",
        "settings.loadModel": "모델을 로드하여 KV 양자화를 설정하세요.",
        "settings.noSessions": "활성 세션 없음",
        "settings.off": "끄기",
        "settings.bit8": "8비트",
        "settings.bit4": "4비트",
        "settings.bit2": "2비트",
        "settings.portError": "오류：포트는 1-65535 범위여야 합니다",
        "settings.adminPortError": "오류：관리 포트는 1-65535 범위여야 합니다",
        "settings.portConflict": "오류：포트와 관리 포트는 달라야 합니다",
        "settings.concurrentError": "오류：최대 동시 연결 수는 0보다 커야 합니다",
        "settings.savedRestart": "저장되었습니다！변경 사항을 적용하려면 앱을 재시작하세요.",
        "settings.systemDefault": "시스템 설정",
        "settings.licenseValue": "Apache 2.0",
        "settings.refresh": "새로고침",
        "settings.clearAll": "전체 삭제",
        "settings.resetCurrent": "현재값으로 재설정",
        "settings.saveToDisk": "디스크에 저장",
        "settings.save": "저장",
        "settings.cancel": "취소",
        "settings.reset": "초기화",
        "settings.memoryLimit": "메모리 제한",
        "settings.memoryLimitAuto": "자동",
        "settings.memoryLimitPercent": "RAM의 %",
        "settings.memoryLimitFixed": "고정 값",
        "settings.memoryLimitAutoDesc": "시스템용으로 max(4GB, 20% RAM) 예약 (최대 8GB). 나머지는 NovaMLX가 사용.",
        "settings.memoryLimitPercentLabel": "백분율",
        "settings.memoryLimitValueLabel": "값",
        "settings.memoryLimitGB": "GB",
        "settings.memoryLimitMB": "MB",

        "agents.integrations": "에이전트 통합",
        "agents.configLabel": "설정",
        "agents.description": "에이전트 도구를 NovaMLX의 추론 백엔드로 연결합니다. NovaMLX는 OpenAI 호환 API를 제공합니다.",
        "agents.serverRunning": "NovaMLX 서버 실행 중：%@",
        "agents.serverNotRunning": "NovaMLX 서버가 중지됨 — 에이전트를 연결할 수 없습니다",
        "agents.installed": "설치됨",
        "agents.notFound": "찾을 수 없음",
        "agents.refreshStatus": "에이전트 상태 새로고침",
        "agents.checkInstalled": "설치된 에이전트 확인",
        "agents.launch": "시작",
        "agents.install": "설치",
        "agents.copyConfig": "설정 복사",
        "agents.configCopied": "%@：설정이 클립보드에 복사되었습니다",
        "agents.launched": "%@：시작됨",
        "agents.launchError": "%@：%@",
        "agents.openclaw": "OpenClaw",
        "agents.hermes": "Hermes Agent",
        "agents.opencode": "OpenCode",
        "agents.openclawDesc": "플러그인 시스템과 도구 사용을 갖춘 오픈소스 AI 에이전트 프레임워크",
        "agents.hermesDesc": "다단계 추론과 도구 실행을 갖춘 자율 AI 에이전트",
        "agents.opencodeDesc": "코드 편집을 지원하는 터미널 기반 AI 프로그래밍 어시스턴트",

        "dashboard.loadedModels": "로드된 모델",
        "dashboard.noModelsLoaded": "로드된 모델 없음",
        "dashboard.availableModels": "사용 가능한 모델",
        "dashboard.noDownloadedModels": "다운로드한 모델을 찾을 수 없습니다",
        "dashboard.system": "시스템",
        "dashboard.used": "사용 중",
        "dashboard.usage": "사용률",
        "dashboard.session": "세션",
        "dashboard.cores": "코어",
        "dashboard.load": "로드",

        "menuBar.openWindow": "창 열기",
        "menuBar.quit": "종료",

        "menu.noModels": "로드된 모델 없음",
        "menu.downloadedCount": "다운로드：%d개 모델",
        "menu.diskUsage": "디스크 사용량：%@",
    ]

    // MARK: - French

    private static let fr: [String: String] = [
        "app.status": "Statut",
        "app.models": "Modèles",
        "app.chat": "Playground",
        "app.agents": "Agents",
        "app.settings": "Paramètres",
        "app.running": "En cours",
        "app.stopped": "Arrêté",
        "app.modelsLoaded": "%d modèle(s) chargé(s)",
        "app.nova": "Nova",
        "app.mlx": "MLX",
        "app.novamlx": "NovaMLX",

        "status.serverOnline": "Serveur en ligne",
        "status.serverOffline": "Serveur hors ligne",
        "status.tokensPerSec": "tokens/sec",
        "status.peakTokensPerSec": "peak tok/s",
        "status.realtimeInferenceSpeed": "Vitesse d'inférence en temps réel",
        "status.noActivity": "Aucune activité d'inférence",
        "status.time": "Temps",
        "status.tokPerSec": "tok/s",
        "status.cpu": "CPU",
        "status.memory": "Mémoire",
        "status.gpu": "GPU",
        "status.uptime": "Disponibilité",
        "status.requests": "Requêtes",
        "status.models": "Modèles",
        "status.disk": "Disque",
        "status.totalTokens": "Total tokens",
        "status.active": "actif",
        "status.loaded": "chargé",
        "status.device": "Appareil",
        "status.chip": "Puce",
        "status.gpuCores": "Cœurs GPU",
        "status.cpuCores": "Cœurs CPU",
        "status.activeModels": "Modèles actifs",
        "status.noModelsLoaded": "Aucun modèle chargé. Allez dans Modèles pour en télécharger et charger un.",
        "status.ready": "Prêt",
        "status.kv": "KV",
        "status.hour": "h",
        "status.minute": "m",
        "status.million": "M",
        "status.thousand": "K",

        "models.myModels": "Mes modèles",
        "models.downloads": "Téléchargements",
        "models.deleteConfirm": "Supprimer le modèle ?",
        "models.deleteMessage": "Cela supprimera définitivement « %@ » du disque. Cette action est irréversible.",
        "models.downloading": "Téléchargement",
        "models.completed": "Terminé",
        "models.noDownloads": "Aucun téléchargement",
        "models.noDownloadsSub": "Recherchez des modèles ou collez une URL pour commencer.",
        "models.noModelsLoaded": "Aucun modèle chargé",
        "models.noModelsLoadedSub": "Chargez un modèle téléchargé pour commencer.",
        "models.noInactiveModels": "Aucun modèle inactif",
        "models.noInactiveModelsSub": "Allez dans Parcourir pour rechercher et télécharger des modèles.",
        "models.searchResults": "Résultats de recherche",
        "models.manualDownload": "Téléchargement manuel",
        "models.search": "Rechercher",
        "models.download": "Télécharger",
        "models.downloaded": "Téléchargé",
        "models.resume": "Reprendre",
        "models.cancel": "Annuler",
        "models.delete": "Supprimer",
        "models.retry": "Réessayer",
        "models.unload": "Décharger",
        "models.load": "Charger",
        "models.close": "Fermer",
        "models.loading": "Chargement...",
        "models.downloadedOk": "Téléchargement réussi",
        "models.retrying": "nouvelle tentative...",
        "models.downloadedLabel": "téléchargé",
        "models.clickDetails": "Cliquez pour voir les détails du modèle",
        "models.openFolder": "Ouvrir le dossier de téléchargement",
        "models.clickCopy": "Cliquez pour copier le chemin",
        "models.urlHint": "Collez un ID de dépôt HuggingFace ou une URL pour télécharger directement.",
        "models.savedTo": "Enregistré dans : %@",
        "models.searchPlaceholder": "Rechercher des modèles HuggingFace...",
        "models.urlPlaceholder": "mlx-community/model-name ou https://huggingface.co/...",
        "models.tags": "Tags",
        "models.specifications": "Spécifications",
        "models.architecture": "Architecture",
        "models.modelType": "Type de modèle",
        "models.license": "Licence",
        "models.language": "Langue",
        "models.family": "Famille",
        "models.type": "Type",
        "models.size": "Taille",
        "models.downloadSize": "Taille du téléchargement",
        "models.diskUsage": "Utilisation disque",
        "models.files": "Fichiers (%d)",
        "models.unknown": "inconnu",
        "models.filesCompleted": "%d/%d fichiers terminés",
        "models.apiKeyRequired": "Clé API requise",
        "models.apiKeyMessage": "L'API d'administration nécessite une clé API pour activer la recherche de modèles.",
        "models.apiKeyLabel": "Clé API :",
        "models.saveRestart": "Enregistrer et redémarrer",
        "models.apiKeyPlaceholder": "sk-novamlx-...",
        "models.invalidUrl": "URL invalide",
        "models.searchFailed": "Échec de la recherche (HTTP %d)",
        "models.noResults": "Aucun résultat pour « %@ »",
        "models.unexpectedFormat": "Format de réponse inattendu",
        "models.searchFailedMsg": "Échec de la recherche : %@",
        "models.invalidHfUrl": "URL HuggingFace invalide",
        "models.invalidUrlMsg": "URL invalide. Format attendu : https://huggingface.co/owner/repo",
        "models.saveFailed": "Échec de l'enregistrement de la clé API : %@",
        "models.gb": "Go",
        "models.mb": "Mo",
        "models.cloudModels": "Modèles cloud",
        "models.noCloudModels": "Aucun modèle cloud disponible",
        "models.noCloudModelsSub": "Les modèles distants apparaîtront ici une fois connecté",

        "chat.model": "Modèle",
        "chat.noModels": "Aucun modèle chargé",
        "chat.clear": "Effacer",
        "chat.toggleParams": "Afficher/masquer les paramètres",
        "chat.rawOutput": "Visualiseur de sortie brute du modèle — non conçu pour un usage quotidien.",
        "chat.webChat": "Chat web",
        "chat.temperature": "Température",
        "chat.topP": "Top P",
        "chat.topK": "Top K",
        "chat.minP": "Min P",
        "chat.maxTokens": "Max tokens",
        "chat.repeatPenalty": "Pénalité de répétition",
        "chat.resetDefault": "Valeurs par défaut",
        "chat.startConversation": "Démarrer une conversation",
        "chat.selectModel": "Sélectionnez un modèle ci-dessus et tapez un message ci-dessous.",
        "chat.you": "Vous",
        "chat.assistant": "Assistant",
        "chat.typePlaceholder": "Tapez un message...",
        "chat.noResponse": "(aucune réponse)",
        "chat.error": "Erreur : %@",
        "chat.thinking": "Réflexion",

        "settings.server": "Serveur",
        "settings.cli": "Outil en ligne de commande",
        "settings.turboQuant": "Quantification KV (TurboQuant)",
        "settings.sessions": "Sessions",
        "settings.about": "À propos",
        "settings.editConfig": "Modifier la config",
        "settings.openChat": "Ouvrir le chat dans le navigateur",
        "settings.openDashboard": "Ouvrir le tableau de bord",
        "settings.openConfig": "Ouvrir le fichier de config",
        "settings.language": "Langue",
        "settings.inferenceApi": "API d'inférence",
        "settings.adminApi": "API d'administration",
        "settings.webChat": "Chat web",
        "settings.adminDashboard": "Tableau de bord admin",
        "settings.configFile": "Fichier de config",
        "settings.version": "Version",
        "settings.build": "Build",
        "settings.license": "Licence",
        "settings.platform": "Plateforme",
        "settings.serverConfig": "Configuration du serveur",
        "settings.host": "Hôte",
        "settings.port": "Port",
        "settings.adminPort": "Port admin",
        "settings.maxConcurrent": "Max concurrent",
        "settings.timeout": "Délai d'attente (s)",
        "settings.maxBody": "Taille max (Mo)",
        "settings.defaultModel": "Modèle par défaut",
        "settings.apiKeys": "Clés API (une par ligne)",
        "settings.clickCopy": "Cliquez pour copier le chemin",
        "settings.hostPlaceholder": "127.0.0.1",
        "settings.modelPlaceholder": "ex : mlx-community/Qwen3-35B-4bit",
        "settings.installCli": "Installer le CLI `nova` dans votre PATH",
        "settings.installed": "Installé",
        "settings.alreadyInstalled": "Déjà installé",
        "settings.cliNotFound": "Binaire CLI introuvable dans l'application",
        "settings.cliInstallSuccess": "Installé ! Ajoutez ~/.local/bin à votre PATH si nécessaire.",
        "settings.turboQuantDesc": "Compresse le cache KV pour réduire la mémoire GPU. Vérifiez la page Statut pour voir l'effet.",
        "settings.loadModel": "Chargez un modèle pour configurer la quantification KV.",
        "settings.noSessions": "Aucune session active",
        "settings.off": "Désactivé",
        "settings.bit8": "8 bits",
        "settings.bit4": "4 bits",
        "settings.bit2": "2 bits",
        "settings.portError": "Erreur : Le port doit être entre 1-65535",
        "settings.adminPortError": "Erreur : Le port admin doit être entre 1-65535",
        "settings.portConflict": "Erreur : Le port et le port admin doivent être différents",
        "settings.concurrentError": "Erreur : Max concurrent doit être > 0",
        "settings.savedRestart": "Enregistré ! Redémarrez l'application pour appliquer.",
        "settings.systemDefault": "Par défaut système",
        "settings.licenseValue": "Apache 2.0",
        "settings.refresh": "Actualiser",
        "settings.clearAll": "Tout effacer",
        "settings.resetCurrent": "Réinitialiser",
        "settings.saveToDisk": "Enregistrer",
        "settings.save": "Enregistrer",
        "settings.cancel": "Annuler",
        "settings.reset": "Réinit.",
        "settings.memoryLimit": "Limite mémoire",
        "settings.memoryLimitAuto": "Auto",
        "settings.memoryLimitPercent": "% de RAM",
        "settings.memoryLimitFixed": "Valeur fixe",
        "settings.memoryLimitAutoDesc": "Réserve max(4Go, 20% RAM) pour le système, plafonné à 8Go. Le reste pour NovaMLX.",
        "settings.memoryLimitPercentLabel": "Pourcentage",
        "settings.memoryLimitValueLabel": "Valeur",
        "settings.memoryLimitGB": "Go",
        "settings.memoryLimitMB": "Mo",

        "agents.integrations": "Intégrations d'agents",
        "agents.configLabel": "Configuration",
        "agents.description": "Connectez des outils d'agents à NovaMLX comme backend d'inférence. NovaMLX expose une API compatible OpenAI.",
        "agents.serverRunning": "Serveur NovaMLX en cours d'exécution : %@",
        "agents.serverNotRunning": "Le serveur NovaMLX n'est pas en cours d'exécution — les agents ne peuvent pas se connecter",
        "agents.installed": "Installé",
        "agents.notFound": "Non trouvé",
        "agents.refreshStatus": "Actualiser le statut des agents",
        "agents.checkInstalled": "Vérifier agents installés",
        "agents.launch": "Lancer",
        "agents.install": "Installer",
        "agents.copyConfig": "Copier la config",
        "agents.configCopied": "%@ : Configuration copiée dans le presse-papiers",
        "agents.launched": "%@ : Lancé",
        "agents.launchError": "%@ : %@",
        "agents.openclaw": "OpenClaw",
        "agents.hermes": "Hermes Agent",
        "agents.opencode": "OpenCode",
        "agents.openclawDesc": "Framework d'agent IA open source avec système de plugins",
        "agents.hermesDesc": "Agent IA autonome avec raisonnement multi-étapes",
        "agents.opencodeDesc": "Assistant de programmation IA en terminal avec édition de code",

        "dashboard.loadedModels": "Modèles chargés",
        "dashboard.noModelsLoaded": "Aucun modèle chargé",
        "dashboard.availableModels": "Modèles disponibles",
        "dashboard.noDownloadedModels": "Aucun modèle téléchargé trouvé",
        "dashboard.system": "système",
        "dashboard.used": "utilisé",
        "dashboard.usage": "utilisation",
        "dashboard.session": "session",
        "dashboard.cores": "cœurs",
        "dashboard.load": "Charger",

        "menuBar.openWindow": "Ouvrir la fenêtre",
        "menuBar.quit": "Quitter",

        "menu.noModels": "Aucun modèle chargé",
        "menu.downloadedCount": "Téléchargés : %d modèle(s)",
        "menu.diskUsage": "Utilisation disque : %@",
    ]

    // MARK: - German

    private static let de: [String: String] = [
        "app.status": "Status",
        "app.models": "Modelle",
        "app.chat": "Playground",
        "app.agents": "Agenten",
        "app.settings": "Einstellungen",
        "app.running": "Aktiv",
        "app.stopped": "Gestoppt",
        "app.modelsLoaded": "%d Modell(e) geladen",
        "app.nova": "Nova",
        "app.mlx": "MLX",
        "app.novamlx": "NovaMLX",

        "status.serverOnline": "Server online",
        "status.serverOffline": "Server offline",
        "status.tokensPerSec": "Tokens/Sek",
        "status.peakTokensPerSec": "Spitze tok/s",
        "status.realtimeInferenceSpeed": "Echtzeit-Inferenzgeschwindigkeit",
        "status.noActivity": "Noch keine Inferenzaktivität",
        "status.time": "Zeit",
        "status.tokPerSec": "tok/s",
        "status.cpu": "CPU",
        "status.memory": "Speicher",
        "status.gpu": "GPU",
        "status.uptime": "Laufzeit",
        "status.requests": "Anfragen",
        "status.models": "Modelle",
        "status.disk": "Festplatte",
        "status.totalTokens": "Gesamt Tokens",
        "status.active": "aktiv",
        "status.loaded": "geladen",
        "status.device": "Gerät",
        "status.chip": "Chip",
        "status.gpuCores": "GPU-Kerne",
        "status.cpuCores": "CPU-Kerne",
        "status.activeModels": "Aktive Modelle",
        "status.noModelsLoaded": "Keine Modelle geladen. Gehen Sie zu Modelle, um eines herunterzuladen.",
        "status.ready": "Bereit",
        "status.kv": "KV",
        "status.hour": "Std",
        "status.minute": "Min",
        "status.million": "M",
        "status.thousand": "K",

        "models.myModels": "Meine Modelle",
        "models.downloads": "Downloads",
        "models.deleteConfirm": "Modell löschen?",
        "models.deleteMessage": "Dies löscht « %@ » dauerhaft von der Festplatte. Dies kann nicht rückgängig gemacht werden.",
        "models.downloading": "Wird heruntergeladen",
        "models.completed": "Abgeschlossen",
        "models.noDownloads": "Keine Downloads",
        "models.noDownloadsSub": "Suchen Sie nach Modellen oder fügen Sie eine URL ein.",
        "models.noModelsLoaded": "Keine Modelle geladen",
        "models.noModelsLoadedSub": "Laden Sie ein heruntergeladenes Modell, um zu beginnen.",
        "models.noInactiveModels": "Keine inaktiven Modelle",
        "models.noInactiveModelsSub": "Gehen Sie zu Durchsuchen, um Modelle zu suchen und herunterzuladen.",
        "models.searchResults": "Suchergebnisse",
        "models.manualDownload": "Manueller Download",
        "models.search": "Suchen",
        "models.download": "Herunterladen",
        "models.downloaded": "Heruntergeladen",
        "models.resume": "Fortsetzen",
        "models.cancel": "Abbrechen",
        "models.delete": "Löschen",
        "models.retry": "Erneut versuchen",
        "models.unload": "Entladen",
        "models.load": "Laden",
        "models.close": "Schließen",
        "models.loading": "Laden...",
        "models.downloadedOk": "Erfolgreich heruntergeladen",
        "models.retrying": "Erneuter Versuch...",
        "models.downloadedLabel": "heruntergeladen",
        "models.clickDetails": "Klicken, um Modelldetails anzuzeigen",
        "models.openFolder": "Download-Ordner öffnen",
        "models.clickCopy": "Klicken, um Pfad zu kopieren",
        "models.urlHint": "HuggingFace-Repo-ID oder URL einfügen, um direkt herunterzuladen.",
        "models.savedTo": "Gespeichert in: %@",
        "models.searchPlaceholder": "HuggingFace-Modelle suchen...",
        "models.urlPlaceholder": "mlx-community/model-name oder https://huggingface.co/...",
        "models.tags": "Tags",
        "models.specifications": "Spezifikationen",
        "models.architecture": "Architektur",
        "models.modelType": "Modelltyp",
        "models.license": "Lizenz",
        "models.language": "Sprache",
        "models.family": "Familie",
        "models.type": "Typ",
        "models.size": "Größe",
        "models.downloadSize": "Download-Größe",
        "models.diskUsage": "Festplattennutzung",
        "models.files": "Dateien (%d)",
        "models.unknown": "unbekannt",
        "models.filesCompleted": "%d/%d Dateien abgeschlossen",
        "models.apiKeyRequired": "API-Schlüssel erforderlich",
        "models.apiKeyMessage": "Die Admin-API benötigt einen API-Schlüssel für die Modellsuche.",
        "models.apiKeyLabel": "API-Schlüssel:",
        "models.saveRestart": "Speichern & Neustarten",
        "models.apiKeyPlaceholder": "sk-novamlx-...",
        "models.invalidUrl": "Ungültige URL",
        "models.searchFailed": "Suche fehlgeschlagen (HTTP %d)",
        "models.noResults": "Keine Ergebnisse für « %@ »",
        "models.unexpectedFormat": "Unerwartetes Antwortformat",
        "models.searchFailedMsg": "Suche fehlgeschlagen: %@",
        "models.invalidHfUrl": "Ungültige HuggingFace-URL",
        "models.invalidUrlMsg": "Ungültige URL. Erwartet: https://huggingface.co/owner/repo",
        "models.saveFailed": "API-Schlüssel konnte nicht gespeichert werden: %@",
        "models.gb": "GB",
        "models.mb": "MB",
        "models.cloudModels": "Cloud-Modelle",
        "models.noCloudModels": "Keine Cloud-Modelle verfügbar",
        "models.noCloudModelsSub": "Remote-Modelle werden bei Verbindung angezeigt",

        "chat.model": "Modell",
        "chat.noModels": "Keine Modelle geladen",
        "chat.clear": "Löschen",
        "chat.toggleParams": "Parametereinstellungen umschalten",
        "chat.rawOutput": "Rohmodell-Ausgabebetrachter — nicht für täglichen Chat gedacht.",
        "chat.webChat": "Web-Chat",
        "chat.temperature": "Temperatur",
        "chat.topP": "Top P",
        "chat.topK": "Top K",
        "chat.minP": "Min P",
        "chat.maxTokens": "Max Tokens",
        "chat.repeatPenalty": "Wiederholungsstrafe",
        "chat.resetDefault": "Standard wiederherstellen",
        "chat.startConversation": "Konversation starten",
        "chat.selectModel": "Wählen Sie oben ein Modell und tippen Sie unten eine Nachricht.",
        "chat.you": "Sie",
        "chat.assistant": "Assistent",
        "chat.typePlaceholder": "Nachricht eingeben...",
        "chat.noResponse": "(keine Antwort)",
        "chat.error": "Fehler: %@",
        "chat.thinking": "Denken",

        "settings.server": "Server",
        "settings.cli": "Kommandozeilen-Tool",
        "settings.turboQuant": "KV-Quantisierung (TurboQuant)",
        "settings.sessions": "Sitzungen",
        "settings.about": "Über",
        "settings.editConfig": "Konfig bearbeiten",
        "settings.openChat": "Chat im Browser öffnen",
        "settings.openDashboard": "Dashboard öffnen",
        "settings.openConfig": "Konfigdatei öffnen",
        "settings.language": "Sprache",
        "settings.inferenceApi": "Inferenz-API",
        "settings.adminApi": "Admin-API",
        "settings.webChat": "Web-Chat",
        "settings.adminDashboard": "Admin-Dashboard",
        "settings.configFile": "Konfigdatei",
        "settings.version": "Version",
        "settings.build": "Build",
        "settings.license": "Lizenz",
        "settings.platform": "Plattform",
        "settings.serverConfig": "Serverkonfiguration",
        "settings.host": "Host",
        "settings.port": "Port",
        "settings.adminPort": "Admin-Port",
        "settings.maxConcurrent": "Max. gleichzeitig",
        "settings.timeout": "Zeitüberschreitung (s)",
        "settings.maxBody": "Max Body (MB)",
        "settings.defaultModel": "Standardmodell",
        "settings.apiKeys": "API-Schlüssel (einer pro Zeile)",
        "settings.clickCopy": "Klicken, um Pfad zu kopieren",
        "settings.hostPlaceholder": "127.0.0.1",
        "settings.modelPlaceholder": "z.B. mlx-community/Qwen3-35B-4bit",
        "settings.installCli": "`nova` CLI im PATH installieren",
        "settings.installed": "Installiert",
        "settings.alreadyInstalled": "Bereits installiert",
        "settings.cliNotFound": "CLI-Binary nicht im App-Bundle gefunden",
        "settings.cliInstallSuccess": "Installiert! Fügen Sie ~/.local/bin zu Ihrem PATH hinzu.",
        "settings.turboQuantDesc": "Komprimiert den KV-Cache, um GPU-Speicher zu reduzieren.",
        "settings.loadModel": "Laden Sie ein Modell, um KV-Quantisierung zu konfigurieren.",
        "settings.noSessions": "Keine aktiven Sitzungen",
        "settings.off": "Aus",
        "settings.bit8": "8-Bit",
        "settings.bit4": "4-Bit",
        "settings.bit2": "2-Bit",
        "settings.portError": "Fehler: Port muss 1-65535 sein",
        "settings.adminPortError": "Fehler: Admin-Port muss 1-65535 sein",
        "settings.portConflict": "Fehler: Port und Admin-Port müssen unterschiedlich sein",
        "settings.concurrentError": "Fehler: Max. gleichzeitig muss > 0 sein",
        "settings.savedRestart": "Gespeichert! App neu starten, um Änderungen zu übernehmen.",
        "settings.systemDefault": "Systemstandard",
        "settings.licenseValue": "Apache 2.0",
        "settings.refresh": "Aktualisieren",
        "settings.clearAll": "Alle löschen",
        "settings.resetCurrent": "Zurücksetzen",
        "settings.saveToDisk": "Speichern",
        "settings.save": "Speichern",
        "settings.cancel": "Abbrechen",
        "settings.reset": "Reset",
        "settings.memoryLimit": "Speicherlimit",
        "settings.memoryLimitAuto": "Auto",
        "settings.memoryLimitPercent": "% RAM",
        "settings.memoryLimitFixed": "Fester Wert",
        "settings.memoryLimitAutoDesc": "Reserviert max(4GB, 20% RAM) für das System, gedeckelt auf 8GB. Der Rest für NovaMLX.",
        "settings.memoryLimitPercentLabel": "Prozent",
        "settings.memoryLimitValueLabel": "Wert",
        "settings.memoryLimitGB": "GB",
        "settings.memoryLimitMB": "MB",

        "agents.integrations": "Agenten-Integrationen",
        "agents.configLabel": "Konfiguration",
        "agents.description": "Verbinden Sie Agenten-Tools mit NovaMLX als Inferenz-Backend. NovaMLX bietet eine OpenAI-kompatible API.",
        "agents.serverRunning": "NovaMLX-Server läuft: %@",
        "agents.serverNotRunning": "NovaMLX-Server läuft nicht — Agenten können sich nicht verbinden",
        "agents.installed": "Installiert",
        "agents.notFound": "Nicht gefunden",
        "agents.refreshStatus": "Agentenstatus aktualisieren",
        "agents.checkInstalled": "Installierte Agents prüfen",
        "agents.launch": "Starten",
        "agents.install": "Installieren",
        "agents.copyConfig": "Konfig kopieren",
        "agents.configCopied": "%@: Konfig in Zwischenablage kopiert",
        "agents.launched": "%@: Gestartet",
        "agents.launchError": "%@: %@",
        "agents.openclaw": "OpenClaw",
        "agents.hermes": "Hermes Agent",
        "agents.opencode": "OpenCode",
        "agents.openclawDesc": "Open-Source-KI-Agenten-Framework mit Plugin-System",
        "agents.hermesDesc": "Autonomer KI-Agent mit mehrstufigem Denken",
        "agents.opencodeDesc": "Terminalbasierter KI-Programmierassistent mit Code-Bearbeitung",

        "dashboard.loadedModels": "Geladene Modelle",
        "dashboard.noModelsLoaded": "Keine Modelle geladen",
        "dashboard.availableModels": "Verfügbare Modelle",
        "dashboard.noDownloadedModels": "Keine heruntergeladenen Modelle gefunden",
        "dashboard.system": "System",
        "dashboard.used": "belegt",
        "dashboard.usage": "Nutzung",
        "dashboard.session": "Sitzung",
        "dashboard.cores": "Kerne",
        "dashboard.load": "Laden",

        "menuBar.openWindow": "Fenster öffnen",
        "menuBar.quit": "Beenden",

        "menu.noModels": "Keine Modelle geladen",
        "menu.downloadedCount": "Heruntergeladen: %d Modell(e)",
        "menu.diskUsage": "Festplattennutzung: %@",
    ]

    // MARK: - Russian

    private static let ru: [String: String] = [
        "app.status": "Статус",
        "app.models": "Модели",
        "app.chat": "Playground",
        "app.agents": "Агенты",
        "app.settings": "Настройки",
        "app.running": "Работает",
        "app.stopped": "Остановлен",
        "app.modelsLoaded": "Загружено моделей: %d",
        "app.nova": "Nova",
        "app.mlx": "MLX",
        "app.novamlx": "NovaMLX",

        "status.serverOnline": "Сервер онлайн",
        "status.serverOffline": "Сервер офлайн",
        "status.tokensPerSec": "токенов/сек",
        "status.peakTokensPerSec": "пик tok/s",
        "status.realtimeInferenceSpeed": "Скорость вывода в реальном времени",
        "status.noActivity": "Нет активности вывода",
        "status.time": "Время",
        "status.tokPerSec": "ток/с",
        "status.cpu": "ЦП",
        "status.memory": "Память",
        "status.gpu": "ГП",
        "status.uptime": "Время работы",
        "status.requests": "Запросы",
        "status.models": "Модели",
        "status.disk": "Диск",
        "status.totalTokens": "Всего токенов",
        "status.active": "активных",
        "status.loaded": "загружено",
        "status.device": "Устройство",
        "status.chip": "Чип",
        "status.gpuCores": "Ядра ГП",
        "status.cpuCores": "Ядра ЦП",
        "status.activeModels": "Активные модели",
        "status.noModelsLoaded": "Модели не загружены. Перейдите в «Модели» для загрузки.",
        "status.ready": "Готов",
        "status.kv": "KV",
        "status.hour": "ч",
        "status.minute": "м",
        "status.million": "М",
        "status.thousand": "К",

        "models.myModels": "Мои модели",
        "models.downloads": "Загрузки",
        "models.deleteConfirm": "Удалить модель?",
        "models.deleteMessage": "«%@» будет навсегда удалена с диска. Это действие нельзя отменить.",
        "models.downloading": "Загрузка",
        "models.completed": "Завершено",
        "models.noDownloads": "Нет загрузок",
        "models.noDownloadsSub": "Найдите модель или вставьте URL для начала загрузки.",
        "models.noModelsLoaded": "Модели не загружены",
        "models.noModelsLoadedSub": "Загрузите скачанную модель для начала работы.",
        "models.noInactiveModels": "Нет неактивных моделей",
        "models.noInactiveModelsSub": "Перейдите к обзору для поиска и загрузки моделей.",
        "models.searchResults": "Результаты поиска",
        "models.manualDownload": "Ручная загрузка",
        "models.search": "Поиск",
        "models.download": "Скачать",
        "models.downloaded": "Скачано",
        "models.resume": "Продолжить",
        "models.cancel": "Отмена",
        "models.delete": "Удалить",
        "models.retry": "Повторить",
        "models.unload": "Выгрузить",
        "models.load": "Загрузить",
        "models.close": "Закрыть",
        "models.loading": "Загрузка...",
        "models.downloadedOk": "Загрузка завершена",
        "models.retrying": "повторная попытка...",
        "models.downloadedLabel": "скачано",
        "models.clickDetails": "Нажмите для просмотра деталей модели",
        "models.openFolder": "Открыть папку загрузок",
        "models.clickCopy": "Нажмите, чтобы скопировать путь",
        "models.urlHint": "Вставьте ID репозитория HuggingFace или URL для прямой загрузки.",
        "models.savedTo": "Сохранено в: %@",
        "models.searchPlaceholder": "Поиск моделей HuggingFace...",
        "models.urlPlaceholder": "mlx-community/model-name или https://huggingface.co/...",
        "models.tags": "Теги",
        "models.specifications": "Характеристики",
        "models.architecture": "Архитектура",
        "models.modelType": "Тип модели",
        "models.license": "Лицензия",
        "models.language": "Язык",
        "models.family": "Семейство",
        "models.type": "Тип",
        "models.size": "Размер",
        "models.downloadSize": "Размер загрузки",
        "models.diskUsage": "Использование диска",
        "models.files": "Файлы (%d)",
        "models.unknown": "неизвестно",
        "models.filesCompleted": "%d/%d файлов завершено",
        "models.apiKeyRequired": "Требуется API-ключ",
        "models.apiKeyMessage": "Для поиска моделей нужен API-ключ. Ключ автоматически сгенерирован ниже.",
        "models.apiKeyLabel": "API-ключ:",
        "models.saveRestart": "Сохранить и перезапустить",
        "models.apiKeyPlaceholder": "sk-novamlx-...",
        "models.invalidUrl": "Неверный URL",
        "models.searchFailed": "Поиск не удался (HTTP %d)",
        "models.noResults": "Ничего не найдено для «%@»",
        "models.unexpectedFormat": "Неожиданный формат ответа",
        "models.searchFailedMsg": "Поиск не удался: %@",
        "models.invalidHfUrl": "Неверный URL HuggingFace",
        "models.invalidUrlMsg": "Неверный URL. Ожидается: https://huggingface.co/owner/repo",
        "models.saveFailed": "Не удалось сохранить API-ключ: %@",
        "models.gb": "ГБ",
        "models.mb": "МБ",
        "models.cloudModels": "Облачные модели",
        "models.noCloudModels": "Облачные модели недоступны",
        "models.noCloudModelsSub": "Удалённые модели появятся при подключении",

        "chat.model": "Модель",
        "chat.noModels": "Модели не загружены",
        "chat.clear": "Очистить",
        "chat.toggleParams": "Настройки параметров",
        "chat.rawOutput": "Просмотр вывода модели — не предназначен для повседневного чата.",
        "chat.webChat": "Веб-чат",
        "chat.temperature": "Температура",
        "chat.topP": "Top P",
        "chat.topK": "Top K",
        "chat.minP": "Min P",
        "chat.maxTokens": "Макс. токенов",
        "chat.repeatPenalty": "Штраф за повтор",
        "chat.resetDefault": "Сбросить настройки",
        "chat.startConversation": "Начать диалог",
        "chat.selectModel": "Выберите модель выше и введите сообщение ниже.",
        "chat.you": "Вы",
        "chat.assistant": "Ассистент",
        "chat.typePlaceholder": "Введите сообщение...",
        "chat.noResponse": "(нет ответа)",
        "chat.error": "Ошибка: %@",
        "chat.thinking": "Размышление",

        "settings.server": "Сервер",
        "settings.cli": "Утилита командной строки",
        "settings.turboQuant": "KV-квантование (TurboQuant)",
        "settings.sessions": "Сессии",
        "settings.about": "О программе",
        "settings.editConfig": "Редактировать конфиг",
        "settings.openChat": "Открыть чат в браузере",
        "settings.openDashboard": "Открыть панель управления",
        "settings.openConfig": "Открыть файл конфигурации",
        "settings.language": "Язык",
        "settings.inferenceApi": "API вывода",
        "settings.adminApi": "API администратора",
        "settings.webChat": "Веб-чат",
        "settings.adminDashboard": "Панель администратора",
        "settings.configFile": "Файл конфигурации",
        "settings.version": "Версия",
        "settings.build": "Сборка",
        "settings.license": "Лицензия",
        "settings.platform": "Платформа",
        "settings.serverConfig": "Конфигурация сервера",
        "settings.host": "Хост",
        "settings.port": "Порт",
        "settings.adminPort": "Порт администратора",
        "settings.maxConcurrent": "Макс. одновременных",
        "settings.timeout": "Таймаут (сек)",
        "settings.maxBody": "Макс. тело (МБ)",
        "settings.defaultModel": "Модель по умолчанию",
        "settings.apiKeys": "API-ключи (по одному на строку)",
        "settings.clickCopy": "Нажмите, чтобы скопировать путь",
        "settings.hostPlaceholder": "127.0.0.1",
        "settings.modelPlaceholder": "напр. mlx-community/Qwen3-35B-4bit",
        "settings.installCli": "Установить CLI `nova` в PATH",
        "settings.installed": "Установлено",
        "settings.alreadyInstalled": "Уже установлено",
        "settings.cliNotFound": "CLI не найден в пакете приложения",
        "settings.cliInstallSuccess": "Установлено! Добавьте ~/.local/bin в PATH.",
        "settings.turboQuantDesc": "Сжимает KV-кэш для уменьшения памяти ГП.",
        "settings.loadModel": "Загрузите модель для настройки KV-квантования.",
        "settings.noSessions": "Нет активных сессий",
        "settings.off": "Выкл",
        "settings.bit8": "8-бит",
        "settings.bit4": "4-бит",
        "settings.bit2": "2-бит",
        "settings.portError": "Ошибка: Порт должен быть 1-65535",
        "settings.adminPortError": "Ошибка: Порт администратора должен быть 1-65535",
        "settings.portConflict": "Ошибка: Порт и порт администратора должны отличаться",
        "settings.concurrentError": "Ошибка: Макс. одновременных должно быть > 0",
        "settings.savedRestart": "Сохранено! Перезапустите приложение для применения.",
        "settings.systemDefault": "Системный",
        "settings.licenseValue": "Apache 2.0",
        "settings.refresh": "Обновить",
        "settings.clearAll": "Очистить все",
        "settings.resetCurrent": "Сбросить",
        "settings.saveToDisk": "Сохранить",
        "settings.save": "Сохранить",
        "settings.cancel": "Отмена",
        "settings.reset": "Сброс",
        "settings.memoryLimit": "Лимит памяти",
        "settings.memoryLimitAuto": "Авто",
        "settings.memoryLimitPercent": "% ОЗУ",
        "settings.memoryLimitFixed": "Фикс. значение",
        "settings.memoryLimitAutoDesc": "Резерв max(4ГБ, 20% ОЗУ) для системы, макс. 8ГБ. Остальное для NovaMLX.",
        "settings.memoryLimitPercentLabel": "Процент",
        "settings.memoryLimitValueLabel": "Значение",
        "settings.memoryLimitGB": "ГБ",
        "settings.memoryLimitMB": "МБ",

        "agents.integrations": "Интеграция агентов",
        "agents.configLabel": "Конфигурация",
        "agents.description": "Подключите инструменты агентов к NovaMLX как серверу вывода. NovaMLX предоставляет API, совместимый с OpenAI.",
        "agents.serverRunning": "Сервер NovaMLX работает: %@",
        "agents.serverNotRunning": "Сервер NovaMLX не запущен — агенты не могут подключиться",
        "agents.installed": "Установлено",
        "agents.notFound": "Не найдено",
        "agents.refreshStatus": "Обновить статус агентов",
        "agents.checkInstalled": "Проверить агентов",
        "agents.launch": "Запустить",
        "agents.install": "Установить",
        "agents.copyConfig": "Копировать конфиг",
        "agents.configCopied": "%@: Конфиг скопирован в буфер обмена",
        "agents.launched": "%@: Запущен",
        "agents.launchError": "%@: %@",
        "agents.openclaw": "OpenClaw",
        "agents.hermes": "Hermes Agent",
        "agents.opencode": "OpenCode",
        "agents.openclawDesc": "Фреймворк ИИ-агентов с открытым исходным кодом и системой плагинов",
        "agents.hermesDesc": "Автономный ИИ-агент с многошаговым рассуждением",
        "agents.opencodeDesc": "Терминальный ИИ-помощник программиста с редактированием кода",

        "dashboard.loadedModels": "Загруженные модели",
        "dashboard.noModelsLoaded": "Модели не загружены",
        "dashboard.availableModels": "Доступные модели",
        "dashboard.noDownloadedModels": "Скачанные модели не найдены",
        "dashboard.system": "система",
        "dashboard.used": "занято",
        "dashboard.usage": "использование",
        "dashboard.session": "сессия",
        "dashboard.cores": "ядра",
        "dashboard.load": "Загрузить",

        "menuBar.openWindow": "Открыть окно",
        "menuBar.quit": "Выход",

        "menu.noModels": "Модели не загружены",
        "menu.downloadedCount": "Скачано: %d мод.",
        "menu.diskUsage": "Использование диска: %@",
    ]
}
