import Foundation
import NovaMLXCore

/// Auto-drafts a `profiles/_drafts/<modelId>.json` test profile for the
/// `novamlx-full-api-test` skill when a model is loaded for the first time
/// and has no matching entry in the bundled or user registry.
///
/// The drafter inspects:
///   • `tokenizer_config.json` for the chat_template + EOS token + thinking-related Jinja vars
///   • `config.json` for architecture and model_type (used by family detection)
///   • added_tokens for VLM/audio/video markers (modality inference)
///
/// The output is a best-effort JSON file flagged as DRAFT. Operators are
/// expected to review it before promoting to `profiles/<key>.json`.
public enum ChatTemplateProfileDrafter {

    /// Draft a profile for `modelId` if one does not already exist on disk.
    /// Returns the path written, or nil when nothing was written (existing
    /// profile, missing model dir, or write failure).
    @discardableResult
    public static func draftIfNeeded(
        modelId: String,
        modelDir: URL,
        family: ModelFamily,
        registryHasOverride: Bool
    ) -> URL? {
        // Where draft profiles live. Sits alongside the `templates/` user
        // override directory in ~/.nova so operators can find both in one place.
        let draftsDir = NovaMLXPaths.baseDir
            .appendingPathComponent("profiles")
            .appendingPathComponent("_drafts")
        let safeName = modelId.replacingOccurrences(of: "/", with: "__")
        let outPath = draftsDir.appendingPathComponent("\(safeName).json")

        let fm = FileManager.default
        // Don't clobber an existing draft (operator may have edited it).
        if fm.fileExists(atPath: outPath.path) {
            return nil
        }
        // Skip if the registry already covers this model (user/built-in maintains it).
        if registryHasOverride {
            return nil
        }

        // Build draft from the model's actual files.
        let draft = buildDraft(modelId: modelId, modelDir: modelDir, family: family)

        // Persist.
        do {
            try fm.createDirectory(at: draftsDir, withIntermediateDirectories: true)
            let data = try JSONSerialization.data(
                withJSONObject: draft,
                options: [.prettyPrinted, .sortedKeys]
            )
            try data.write(to: outPath, options: .atomic)
            NovaMLXLog.info("[ProfileDrafter] wrote draft profile for \(modelId) → \(outPath.path) (review before promoting)")
            return outPath
        } catch {
            NovaMLXLog.warning("[ProfileDrafter] failed to write draft for \(modelId): \(error.localizedDescription)")
            return nil
        }
    }

    // MARK: - Internal

    private static func buildDraft(modelId: String, modelDir: URL, family: ModelFamily) -> [String: Any] {
        var draft: [String: Any] = [
            "$schema": "https://novamlx.dev/test-profile.v1.json",
            "name": "DRAFT — \(modelId)",
            "_drafted_at": ISO8601DateFormatter().string(from: Date()),
            "_review_required": true,
            "_doc": "Auto-generated by ChatTemplateProfileDrafter at first model load. Inspect, edit, and move out of _drafts/ to activate. The skill `novamlx-full-api-test` will use it when this exact modelId is loaded.",
            "matches": [
                "modelIds": [modelId],
                "families": [family.rawValue],
            ],
            "modelCardURL": NSNull(),
            "notes": "Auto-drafted; please verify by consulting the model card.",
        ]

        // Inspect tokenizer_config.json
        let tcPath = modelDir.appendingPathComponent("tokenizer_config.json")
        var template: String = ""
        var eosToken: String? = nil
        if let data = try? Data(contentsOf: tcPath),
           let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            template = (json["chat_template"] as? String) ?? ""
            eosToken = json["eos_token"] as? String
        }

        // Detect thinking support from template Jinja variable presence.
        let supportsEnableThinking = template.contains("enable_thinking is")
            || template.contains("enable_thinking ==")
            || template.contains("enable_thinking is defined")
        let supportsPreserveThinking = template.contains("preserve_thinking is")
            || template.contains("preserve_thinking ==")
            || template.contains("preserve_thinking is defined")
        let usesThinkTags = template.contains("<think>") || template.contains("<thinking>")
        let usesBeginOfThought = template.contains("begin_of_thought")

        // Modality inference: presence of vision/image/audio/video markers in
        // template suggests the model accepts those inputs.
        var modality: [String] = ["text"]
        if template.contains("vision") || template.contains("image_pad") {
            modality.append("image")
        }
        if template.contains("audio_pad") {
            modality.append("audio")
        }
        if template.contains("video_pad") {
            modality.append("video")
        }

        // Capabilities — best-effort defaults
        let capabilities: [String: Any] = [
            "thinking": (usesThinkTags || usesBeginOfThought) ? "hybrid" : "none",
            "thinking_default_on": template.contains("<think>\\n"),
            "disable_methods": supportsEnableThinking
                ? ["chat_template_kwargs.enable_thinking", "enable_thinking"]
                : [],
            "soft_switch": template.contains("/think") || template.contains("/no_think"),
            "preserve_thinking": supportsPreserveThinking,
            "modality": modality,
            "tool_calling": template.contains("tool_call") || template.contains("<tools>"),
            "structured_output": true,
            "embeddings": false,
        ]
        draft["capabilities"] = capabilities

        // Sampling — defer to family defaults via registry
        let famCfg = ChatTemplateRegistry.shared.familyConfig(for: family)
        let conservative: [String: Any] = [
            "temperature": 0.7,
            "top_p": 0.9,
            "top_k": 40,
            "min_p": 0.0,
            "presence_penalty": 0.0,
            "repetition_penalty": 1.0,
        ]
        let thinkingSampling: Any = (usesThinkTags || usesBeginOfThought) ? conservative : NSNull()
        draft["sampling"] = [
            "thinking_general": thinkingSampling,
            "thinking_coding": thinkingSampling,
            "non_thinking": conservative,
            "forbid_greedy": false,
        ] as [String: Any]
        draft["max_tokens"] = [
            "thinking": 4096,
            "non_thinking": 1024,
            "vlm": modality.contains("image") ? 1024 : 0,
        ]

        // Control tokens — seed from registry's family config.
        // We deliberately do NOT add the model's actual EOS token to the
        // leakage blacklist; the API layer needs it as a stop signal.
        let leakage = famCfg.leakageBlacklist
        draft["control_tokens"] = [
            "expected_eos": famCfg.expectedEosTokens.isEmpty
                ? (eosToken.map { [$0] } ?? [])
                : famCfg.expectedEosTokens,
            "leakage_blacklist": leakage,
            "hallucination_patterns": famCfg.hallucinationPatterns,
            "thinking_markers_keep": famCfg.thinkingMarkers,
        ]

        draft["expected_format"] = [
            "vendor_thinking": usesThinkTags ? "<think>...</think>" : NSNull(),
            "answer_after_thinking": usesThinkTags || usesBeginOfThought,
            "answer_max_chars_simple": 100,
        ]

        draft["test_overrides"] = [
            "T1.expected_answer_regex": "\\b(4|four)\\b",
            "T5.system_prompt_marker_regex": "(?i)\\barrr\\b",
            "T10.regression_prompt": "Say hello in one short sentence.",
        ]

        return draft
    }
}
